Repository nmshd/runtime, pull requests merged in 2024-08, with the labels that each got.

#238 Update app-runtime config value `dataFolder` to `databaseFolder` to align naming and actual usage
  packages/app-runtime/src/AppConfig.ts
  packages/app-runtime/src/AppRuntime.ts
Labels: bug

#239 Properly authentication to npmjs during publish
  .github/workflows/publish.yml
Labels: ci

#227 Block new Relationship creation if old Relationship is not yet fully decomposed
  packages/consumption/test/modules/requests/IncomingRequestsController.test.ts
  packages/consumption/test/modules/requests/RequestsIntegrationTest.ts
  packages/consumption/test/modules/requests/testHelpers/TestObjectFactory.ts
  packages/runtime/src/modules/RequestModule.ts
  packages/runtime/test/lib/testUtils.ts
  packages/runtime/test/modules/RequestModule.test.ts
  packages/runtime/test/transport/relationships.test.ts
  packages/transport/src/core/CoreErrors.ts
  packages/transport/src/modules/relationships/RelationshipsController.ts
Labels: enhancement

#192 Prohibit sharing RelationshipAttributes of pending Relationships
  packages/consumption/src/consumption/CoreErrors.ts
  packages/consumption/src/modules/requests/itemProcessors/readAttribute/ReadAttributeRequestItemProcessor.ts
  packages/consumption/src/modules/requests/itemProcessors/shareAttribute/ShareAttributeRequestItemProcessor.ts
  packages/consumption/test/core/TestUtil.ts
  packages/consumption/test/modules/requests/itemProcessors/readAttribute/ReadAttributeRequestItemProcessor.test.ts
  packages/consumption/test/modules/requests/itemProcessors/shareAttribute/ShareAttributeRequestItemProcessor.test.ts
  packages/consumption/test/modules/requests/itemProcessors/utility/validateAttributeMatchesWithQuery.test.ts
  packages/runtime/src/modules/AttributeListenerModule.ts
  packages/runtime/test/lib/testUtils.ts
  packages/runtime/test/modules/AttributeListenerModule.test.ts
Labels: enhancement

#243 Remove unused ConsumptionControllerNames
  packages/consumption/src/consumption/ConsumptionControllerName.ts
Labels: chore

#244 simplify
  .ci/runChecks.sh
  package-lock.json
  packages/app-runtime/src/AppConfig.ts
  packages/app-runtime/src/AppRuntime.ts
  packages/consumption/src/consumption/Consumption.ts
  packages/consumption/src/consumption/ConsumptionConfig.ts
  packages/consumption/src/consumption/ConsumptionController.ts
  packages/consumption/src/consumption/index.ts
  packages/consumption/test/core/TestUtil.ts
  packages/consumption/test/modules/attributeListeners/AttributeListenersController.test.ts
  packages/consumption/test/modules/attributes/AttributesController.test.ts
  packages/consumption/test/modules/attributes/LocalAttributeDeletionInfo.test.ts
  packages/consumption/test/modules/notifications/NotificationEnd2End.test.ts
  packages/consumption/test/modules/notifications/NotificationsController.test.ts
  packages/consumption/test/modules/notifications/itemProcessors/attributeDeleted/OwnSharedAttributeDeletedByOwnerNotificationItemProcessor.test.ts
  packages/consumption/test/modules/notifications/itemProcessors/attributeDeleted/PeerSharedAttributeDeletedByPeerNotificationItemProcessor.test.ts
  packages/consumption/test/modules/notifications/itemProcessors/attributeDeleted/ThirdPartyOwnedRelationshipAttributeDeletedByPeerNotificationItemProcessor.test.ts
  packages/consumption/test/modules/notifications/itemProcessors/attributeSucceeded/PeerSharedAttributeSucceededNotificationItemProcessor.test.ts
  packages/consumption/test/modules/requests/DeleteRequest.test.ts
  packages/consumption/test/modules/requests/RequestEnd2End.test.ts
  packages/consumption/test/modules/requests/RequestsIntegrationTest.ts
  packages/consumption/test/modules/requests/itemProcessors/createAttribute/Context.ts
  packages/consumption/test/modules/requests/itemProcessors/deleteAttribute/DeleteAttributeRequestItemProcessor.test.ts
  packages/consumption/test/modules/requests/itemProcessors/freeText/FreeTextRequestItemProcessor.test.ts
  packages/consumption/test/modules/requests/itemProcessors/proposeAttribute/ProposeAttributeRequestItemProcessor.test.ts
  packages/consumption/test/modules/requests/itemProcessors/readAttribute/ReadAttributeRequestItemProcessor.test.ts
  packages/consumption/test/modules/requests/itemProcessors/registerAttributeListener/RegisterAttributeListenerRequestItemProcessor.test.ts
  packages/consumption/test/modules/requests/itemProcessors/shareAttribute/ShareAttributeRequestItemProcessor.test.ts
  packages/consumption/test/modules/requests/itemProcessors/utility/validateAttributeMatchesWithQuery.test.ts
  packages/runtime/src/Runtime.ts
  packages/runtime/src/RuntimeConfig.ts
  packages/runtime/src/useCases/consumption/attributes/ChangeDefaultRepositoryAttribute.ts
  packages/runtime/test/lib/RuntimeServiceProvider.ts
  packages/runtime/test/lib/TestRuntime.ts
  packages/runtime/test/misc/DatabaseSchemaUpgrader.test.ts
Labels: refactoring

#240 Move natives to app runtime
  package-lock.json
  packages/app-runtime/package.json
  packages/app-runtime/src/AppRuntime.ts
  packages/app-runtime/src/index.ts
  packages/app-runtime/src/modules/AppRuntimeModule.ts
  packages/app-runtime/src/modules/appEvents/AppLaunchModule.ts
  packages/app-runtime/src/modules/pushNotifications/PushNotificationModule.ts
  packages/app-runtime/src/natives/INativeBootstrapper.ts
  packages/app-runtime/src/natives/INativeConfigAccess.ts
  packages/app-runtime/src/natives/INativeDeviceInfoAccess.ts
  packages/app-runtime/src/natives/INativeEnvironment.ts
  packages/app-runtime/src/natives/INativeNotificationAccess.ts
  packages/app-runtime/src/natives/INativeTranslationProvider.ts
  packages/app-runtime/src/natives/NativeEvent.ts
  packages/app-runtime/src/natives/events/AppReadyEvent.ts
  packages/app-runtime/src/natives/events/RemoteNotificationEvent.ts
  packages/app-runtime/src/natives/events/RemoteNotificationRegistrationEvent.ts
  packages/app-runtime/src/natives/events/UrlOpenEvent.ts
  packages/app-runtime/src/natives/events/index.ts
  packages/app-runtime/src/natives/index.ts
  packages/app-runtime/src/runtimeNatives.ts
  packages/app-runtime/test/mocks/NativeAuthenticationAccessMock.ts
  packages/app-runtime/test/mocks/NativeBootstrapperMock.ts
  packages/app-runtime/test/mocks/NativeConfigAccessMock.ts
  packages/app-runtime/test/mocks/NativeDeviceInfoAccessMock.ts
  packages/app-runtime/test/mocks/NativeEventBusMock.ts
  packages/app-runtime/test/mocks/NativeFileAccessMock.ts
  packages/app-runtime/test/mocks/NativeKeychainAccessMock.ts
  packages/app-runtime/test/mocks/NativeLoggerFactoryMock.ts
  packages/app-runtime/test/mocks/NativeNotificationAccessMock.ts
  packages/app-runtime/test/mocks/NativePushNotificationAccessMock.ts
  packages/app-runtime/test/mocks/NativeScannerAccessMock.ts
  packages/app-runtime/test/modules/PushNotification.test.ts
  packages/app-runtime/test/runtime/TranslationProvider.test.ts
Labels: refactoring

#241 Add configuration for setting isDefault of LocalAttributes
  package-lock.json
  packages/app-runtime/src/AppRuntime.ts
  packages/consumption/src/consumption/ConsumptionConfig.ts
  packages/consumption/src/consumption/ConsumptionController.ts
  packages/consumption/src/consumption/CoreErrors.ts
  packages/consumption/src/index.ts
  packages/consumption/src/modules/attributes/AttributesController.ts
  packages/consumption/test/core/TestUtil.ts
  packages/consumption/test/modules/attributeListeners/AttributeListenersController.test.ts
  packages/consumption/test/modules/attributes/AttributesController.test.ts
  packages/consumption/test/modules/attributes/LocalAttributeDeletionInfo.test.ts
  packages/consumption/test/modules/notifications/itemProcessors/attributeDeleted/OwnSharedAttributeDeletedByOwnerNotificationItemProcessor.test.ts
  packages/consumption/test/modules/notifications/itemProcessors/attributeDeleted/PeerSharedAttributeDeletedByPeerNotificationItemProcessor.test.ts
  packages/consumption/test/modules/notifications/itemProcessors/attributeDeleted/ThirdPartyOwnedRelationshipAttributeDeletedByPeerNotificationItemProcessor.test.ts
  packages/consumption/test/modules/notifications/itemProcessors/attributeSucceeded/PeerSharedAttributeSucceededNotificationItemProcessor.test.ts
  packages/consumption/test/modules/requests/itemProcessors/deleteAttribute/DeleteAttributeRequestItemProcessor.test.ts
  packages/consumption/test/modules/requests/itemProcessors/freeText/FreeTextRequestItemProcessor.test.ts
  packages/consumption/test/modules/requests/itemProcessors/proposeAttribute/ProposeAttributeRequestItemProcessor.test.ts
  packages/consumption/test/modules/requests/itemProcessors/readAttribute/ReadAttributeRequestItemProcessor.test.ts
  packages/consumption/test/modules/requests/itemProcessors/registerAttributeListener/RegisterAttributeListenerRequestItemProcessor.test.ts
  packages/consumption/test/modules/requests/itemProcessors/shareAttribute/ShareAttributeRequestItemProcessor.test.ts
  packages/consumption/test/modules/requests/itemProcessors/utility/validateAttributeMatchesWithQuery.test.ts
  packages/runtime/src/useCases/common/RuntimeErrors.ts
  packages/runtime/src/useCases/consumption/attributes/ChangeDefaultRepositoryAttribute.ts
  packages/runtime/test/consumption/attributes.test.ts
  packages/runtime/test/dataViews/IdentityAttributeQueryExpanded.test.ts
  packages/runtime/test/lib/RuntimeServiceProvider.ts
  packages/runtime/test/lib/TestRuntime.ts
  packages/runtime/test/misc/DatabaseSchemaUpgrader.test.ts
Labels: enhancement

#247 DatabaseFolder config from nativeEnvironment is ignored
  packages/app-runtime/src/AppRuntime.ts
Labels: bug

#248 Package versions does not land in the buildInformation
  .ci/writeBuildInformation.sh
  .github/workflows/publish.yml
Labels: bug

#208 Validate Backbone Compatibility
  .ci/runChecks.sh
  package-lock.json
  packages/runtime/src/Runtime.ts
  packages/runtime/src/extensibility/AnonymousServices.ts
  packages/runtime/src/extensibility/facades/anonymous/BackboneCompatibilityFacade.ts
  packages/runtime/src/extensibility/facades/anonymous/index.ts
  packages/runtime/src/useCases/anonymous/backboneCompatibility/CheckBackboneCompatibilityUseCase.ts
  packages/runtime/src/useCases/anonymous/backboneCompatibility/index.ts
  packages/runtime/src/useCases/anonymous/index.ts
  packages/runtime/test/anonymous/backboneCompatibility.test.ts
  packages/transport/src/core/Transport.ts
  packages/transport/src/modules/backboneCompatibility/BackboneCompatibilityController.ts
  packages/transport/src/modules/backboneCompatibility/backbone/GetBackboneVersionResponse.ts
  packages/transport/src/modules/backboneCompatibility/backbone/VersionClient.ts
  packages/transport/src/modules/index.ts
  packages/transport/test/modules/backboneCompatibility/BackboneCompatibilityController.test.ts
Labels: enhancement

#250 Empty owner instead of explicit address for ShareAttributeRequestItem
  package-lock.json
  packages/consumption/src/modules/requests/itemProcessors/shareAttribute/ShareAttributeRequestItemProcessor.ts
  packages/consumption/test/modules/requests/itemProcessors/shareAttribute/ShareAttributeRequestItemProcessor.test.ts
Labels: bug

#246 Do not use consumption types in runtime DTOs
  packages/consumption/src/modules/attributes/AttributesController.ts
  packages/consumption/src/modules/attributes/local/LocalAttribute.ts
  packages/consumption/src/modules/attributes/local/LocalAttributeDeletionInfo.ts
  packages/consumption/src/modules/notifications/itemProcessors/attributeDeleted/OwnSharedAttributeDeletedByOwnerNotificationItemProcessor.ts
  packages/consumption/src/modules/notifications/itemProcessors/attributeDeleted/PeerSharedAttributeDeletedByPeerNotificationItemProcessor.ts
  packages/consumption/src/modules/notifications/itemProcessors/attributeDeleted/ThirdPartyOwnedRelationshipAttributeDeletedByPeerNotificationItemProcessor.ts
  packages/consumption/src/modules/requests/itemProcessors/deleteAttribute/DeleteAttributeRequestItemProcessor.ts
  packages/consumption/src/modules/requests/itemProcessors/proposeAttribute/ProposeAttributeRequestItemProcessor.ts
  packages/consumption/src/modules/requests/itemProcessors/readAttribute/ReadAttributeRequestItemProcessor.ts
  packages/consumption/src/modules/requests/itemProcessors/shareAttribute/ShareAttributeRequestItemProcessor.ts
  packages/consumption/src/modules/requests/outgoing/OutgoingRequestsController.ts
  packages/consumption/test/modules/attributes/AttributesController.test.ts
  packages/consumption/test/modules/attributes/LocalAttributeDeletionInfo.test.ts
  packages/consumption/test/modules/notifications/itemProcessors/attributeDeleted/OwnSharedAttributeDeletedByOwnerNotificationItemProcessor.test.ts
  packages/consumption/test/modules/notifications/itemProcessors/attributeDeleted/PeerSharedAttributeDeletedByPeerNotificationItemProcessor.test.ts
  packages/consumption/test/modules/notifications/itemProcessors/attributeDeleted/ThirdPartyOwnedRelationshipAttributeDeletedByPeerNotificationItemProcessor.test.ts
  packages/consumption/test/modules/requests/RequestsIntegrationTest.ts
  packages/consumption/test/modules/requests/itemProcessors/deleteAttribute/DeleteAttributeRequestItemProcessor.test.ts
  packages/consumption/test/modules/requests/itemProcessors/proposeAttribute/ProposeAttributeRequestItemProcessor.test.ts
  packages/consumption/test/modules/requests/itemProcessors/readAttribute/ReadAttributeRequestItemProcessor.test.ts
  packages/consumption/test/modules/requests/itemProcessors/shareAttribute/ShareAttributeRequestItemProcessor.test.ts
  packages/content/src/attributes/ThirdPartyRelationshipAttributeQuery.ts
  packages/runtime/src/types/consumption/LocalAttributeDTO.ts
  packages/runtime/src/types/consumption/LocalNotificationDTO.ts
  packages/runtime/src/types/consumption/LocalRequestDTO.ts
  packages/runtime/src/types/consumption/SettingDTO.ts
  packages/runtime/src/types/transport/IdentityDeletionProcessDTO.ts
  packages/runtime/test/consumption/attributes.test.ts
  packages/runtime/test/consumption/iqlQuery.test.ts
  packages/runtime/test/consumption/notifications.test.ts
  packages/runtime/test/consumption/requests.test.ts
  packages/runtime/test/dataViews/IdentityDVO.test.ts
  packages/runtime/test/dataViews/RelationshipTemplateDVO.test.ts
  packages/runtime/test/dataViews/requestItems/ComplexReadAttributeRequestItemDVO.test.ts
  packages/runtime/test/dataViews/requestItems/CreateIdentityAttributeRequestItemDVO.test.ts
  packages/runtime/test/dataViews/requestItems/CreateRelationshipAttributeRequestItemDVO.test.ts
  packages/runtime/test/dataViews/requestItems/DeleteAttributeRequestItemDVO.test.ts
  packages/runtime/test/dataViews/requestItems/FreeTextRequestItemDVO.test.ts
  packages/runtime/test/dataViews/requestItems/ProposeAttributeRequestItemDVO.test.ts
  packages/runtime/test/dataViews/requestItems/ReadAttributeRequestItemDVO.test.ts
  packages/runtime/test/dataViews/requestItems/ShareAttributeRequestItemDVO.test.ts
  packages/runtime/test/lib/testUtils.ts
  packages/runtime/test/misc/DatabaseSchemaUpgrader.test.ts
  packages/runtime/test/modules/DeciderModule.test.ts
  packages/runtime/test/modules/NotificationModule.test.ts
  packages/runtime/test/modules/RequestModule.test.ts
Labels: refactoring

#252 RelationshipChangedEvent is triggered even if the Relationship has not changed
  .dev/compose.backbone.env
  packages/transport/src/modules/relationships/RelationshipsController.ts
  packages/transport/src/modules/sync/externalEventProcessors/RelationshipExternalEventProcessor.ts
  packages/transport/src/modules/sync/externalEventProcessors/RelationshipReactivationCompletedExternalEventProcessor.ts
  packages/transport/src/modules/sync/externalEventProcessors/RelationshipReactivationRequestedExternalEventProcessor.ts
  packages/transport/src/modules/sync/externalEventProcessors/RelationshipStatusChangedExternalEventProcessor.ts
  packages/transport/test/modules/relationships/TerminateDecompose.test.ts
Labels: bug

#253 ExternalEventProcessor naming
  packages/transport/src/modules/sync/externalEventProcessors/ExternalEventProcessorRegistry.ts
  packages/transport/src/modules/sync/externalEventProcessors/IdentityDeletionProcessChangedExternalEventProcessor.ts
  packages/transport/src/modules/sync/externalEventProcessors/IdentityDeletionProcessStartedExternalEventProcessor.ts
  packages/transport/src/modules/sync/externalEventProcessors/index.ts
Labels: chore

#223 Process the identity deletion of peers
  packages/runtime/src/dataViews/DataViewExpander.ts
  packages/runtime/src/dataViews/transport/RelationshipDVO.ts
  packages/runtime/src/events/EventProxy.ts
  packages/runtime/src/events/transport/PeerDeletedEvent.ts
  packages/runtime/src/events/transport/PeerDeletionCancelledEvent.ts
  packages/runtime/src/events/transport/PeerToBeDeletedEvent.ts
  packages/runtime/src/events/transport/index.ts
  packages/runtime/src/types/transport/RelationshipDTO.ts
  packages/runtime/src/useCases/transport/relationships/RelationshipMapper.ts
  packages/runtime/test/lib/testUtils.ts
  packages/runtime/test/transport/identityDeletionPeerProcessing.test.ts
  packages/transport/src/events/PeerDeletedEvent.ts
  packages/transport/src/events/PeerDeletionCancelledEvent.ts
  packages/transport/src/events/PeerToBeDeletedEvent.ts
  packages/transport/src/events/index.ts
  packages/transport/src/modules/index.ts
  packages/transport/src/modules/relationships/RelationshipsController.ts
  packages/transport/src/modules/relationships/local/PeerDeletionInfo.ts
  packages/transport/src/modules/relationships/local/Relationship.ts
  packages/transport/src/modules/sync/externalEventProcessors/ExternalEventProcessorRegistry.ts
  packages/transport/src/modules/sync/externalEventProcessors/PeerDeletedExternalEventProcessor.ts
  packages/transport/src/modules/sync/externalEventProcessors/PeerDeletionCancelledExternalEventProcessor.ts
  packages/transport/src/modules/sync/externalEventProcessors/PeerToBeDeletedExternalEventProcessor.ts
  packages/transport/test/modules/sync/externalEventProcessors/PeerDeletedExternalEventProcessor.test.ts
  packages/transport/test/modules/sync/externalEventProcessors/PeerDeletionCancelledExternalEvent.test.ts
  packages/transport/test/modules/sync/externalEventProcessors/PeerToBeDeletedExternalEventProcessor.test.ts
Labels: enhancement

#255 Move codecov to the fastest tests
  .github/workflows/test.yml
Labels: ci

#258 Re-enable coverage for many libs
  packages/consumption/package.json
  packages/runtime/package.json
  packages/transport/package.json
Labels: chore
