Repository nmshd/runtime, pull requests merged in 2024-09, with the labels that each got.

#261 Upsert settings
  packages/runtime/src/extensibility/facades/consumption/SettingsFacade.ts
  packages/runtime/src/useCases/common/Schemas.ts
  packages/runtime/src/useCases/consumption/settings/UpsertSettingByKey.ts
  packages/runtime/src/useCases/consumption/settings/index.ts
  packages/runtime/test/consumption/settings.test.ts
Labels: enhancement

#263 Fix/Failing initial sync breaks AccountController
  packages/app-runtime/src/multiAccount/MultiAccountController.ts
  packages/transport/src/core/TransportCoreErrors.ts
  packages/transport/src/modules/accounts/AccountController.ts
Labels: bug

#266 Simplify Decider module
  packages/runtime/src/modules/DeciderModule.ts
  packages/runtime/test/modules/DeciderModule.test.ts
Labels: refactoring

#267 Apply code and message to RejectResponseItem
  packages/consumption/src/modules/requests/itemProcessors/GenericRequestItemProcessor.ts
  packages/consumption/test/modules/requests/GenericRequestItemProcessor.test.ts
  packages/consumption/test/modules/requests/IncomingRequestsController.test.ts
Labels: bug

#268 Add correlation ID to all use cases and send it to backbone
  package-lock.json
  packages/runtime/src/useCases/common/UseCase.ts
  packages/runtime/test/lib/RequestInterceptor.ts
  packages/runtime/test/misc/CorrelationId.test.ts
  packages/transport/package.json
  packages/transport/src/core/backbone/RESTClient.ts
  packages/transport/test/core/backbone/Authentication.test.ts
  packages/transport/test/core/backbone/CorrelationId.test.ts
Labels: enhancement

#273 Stabilize IdentityDeletionPeerProcessing test
  packages/runtime/test/transport/identityDeletionPeerProcessing.test.ts
Labels: test

#271 Change the message of "error.consumption.validation.inheritedFromItem" when using canCreate
  packages/consumption/src/consumption/ConsumptionCoreErrors.ts
  packages/consumption/src/modules/common/ValidationResult.ts
  packages/consumption/src/modules/requests/outgoing/OutgoingRequestsController.ts
  packages/consumption/test/modules/requests/DecideRequestParametersValidator.test.ts
  packages/consumption/test/modules/requests/IncomingRequestsController.test.ts
  packages/consumption/test/modules/requests/OutgoingRequestsController.test.ts
  packages/consumption/test/modules/requests/RequestsIntegrationTest.ts
Labels: refactoring

#3 Identity Metadata
  package-lock.json
  packages/consumption/src/consumption/ConsumptionController.ts
  packages/consumption/src/consumption/ConsumptionControllerName.ts
  packages/consumption/src/consumption/ConsumptionIds.ts
  packages/consumption/src/modules/identityMetadata/IdentityMetadataController.ts
  packages/consumption/src/modules/identityMetadata/index.ts
  packages/consumption/src/modules/identityMetadata/local/IdentityMetadata.ts
  packages/consumption/src/modules/identityMetadata/local/UpsertIdentityMetadataParams.ts
  packages/consumption/src/modules/index.ts
  packages/consumption/test/modules/identityMetadata/IdentityMetadataController.test.ts
  packages/runtime/src/Runtime.ts
  packages/runtime/src/extensibility/ConsumptionServices.ts
  packages/runtime/src/extensibility/facades/consumption/IdentityMetadataFacade.ts
  packages/runtime/src/extensibility/facades/consumption/index.ts
  packages/runtime/src/types/consumption/IdentityMetadataDTO.ts
  packages/runtime/src/types/consumption/index.ts
  packages/runtime/src/useCases/common/Schemas.ts
  packages/runtime/src/useCases/consumption/identityMetadata/DeleteIdentityMetadata.ts
  packages/runtime/src/useCases/consumption/identityMetadata/GetIdentityMetadata.ts
  packages/runtime/src/useCases/consumption/identityMetadata/IdentityMetadataMapper.ts
  packages/runtime/src/useCases/consumption/identityMetadata/UpsertIdentityMetadata.ts
  packages/runtime/src/useCases/consumption/identityMetadata/index.ts
  packages/runtime/src/useCases/consumption/index.ts
  packages/runtime/test/consumption/identityMetadata.test.ts
Labels: enhancement

#274 Make relationship setting usable
  packages/runtime/src/dataViews/DataViewExpander.ts
  packages/runtime/src/dataViews/transport/IdentityDVO.ts
  packages/runtime/src/dataViews/transport/RelationshipDVO.ts
  packages/runtime/src/useCases/common/Schemas.ts
  packages/runtime/src/useCases/consumption/settings/GetSettingByKey.ts
  packages/runtime/src/useCases/consumption/settings/UpsertSettingByKey.ts
  packages/runtime/test/consumption/settings.test.ts
  packages/runtime/test/dataViews/RelationshipDVO.test.ts
Labels: refactoring

#276 Use `correlation-id` package only for testing
  package-lock.json
  packages/runtime/src/Runtime.ts
  packages/runtime/src/useCases/common/AbstractCorrelator.ts
  packages/runtime/src/useCases/common/UseCase.ts
  packages/runtime/src/useCases/index.ts
  packages/runtime/test/lib/RuntimeServiceProvider.ts
  packages/runtime/test/lib/TestRuntime.ts
  packages/runtime/test/misc/CorrelationId.test.ts
  packages/transport/package.json
  packages/transport/src/core/ICorrelator.ts
  packages/transport/src/core/Transport.ts
  packages/transport/src/core/backbone/Authenticator.ts
  packages/transport/src/core/backbone/RESTClient.ts
  packages/transport/src/core/backbone/RESTClientAuthenticate.ts
  packages/transport/src/core/index.ts
  packages/transport/src/modules/accounts/AccountController.ts
  packages/transport/src/modules/accounts/IdentityDeletionProcessController.ts
  packages/transport/src/modules/backboneCompatibility/BackboneCompatibilityController.ts
  packages/transport/src/modules/challenges/ChallengeController.ts
  packages/transport/src/modules/devices/DevicesController.ts
  packages/transport/src/modules/files/FileController.ts
  packages/transport/src/modules/messages/MessageController.ts
  packages/transport/src/modules/relationshipTemplates/RelationshipTemplateController.ts
  packages/transport/src/modules/relationships/RelationshipsController.ts
  packages/transport/src/modules/sync/SyncController.ts
  packages/transport/src/modules/sync/backbone/SyncClient.ts
  packages/transport/src/modules/tokens/AnonymousTokenController.ts
  packages/transport/src/modules/tokens/TokenController.ts
  packages/transport/test/core/backbone/CorrelationId.test.ts
  packages/transport/test/testHelpers/TestUtil.ts
Labels: bug

#277 Remove expectThrowsAsync
  packages/app-runtime/test/lib/TestUtil.ts
  packages/consumption/test/core/TestUtil.ts
  packages/consumption/test/modules/attributes/AttributesController.test.ts
  packages/consumption/test/modules/requests/RequestsIntegrationTest.ts
  packages/content/test/requests/Request.test.ts
  packages/content/test/requests/Response.test.ts
  packages/content/test/testUtils.ts
  packages/transport/test/modules/devices/DeviceOnboarding.test.ts
  packages/transport/test/modules/relationshipTemplates/RelationshipTemplateController.test.ts
  packages/transport/test/testHelpers/TestUtil.ts
Labels: test

#280 Sharing a request with yourself shows a misleading error message
  packages/consumption/src/consumption/ConsumptionCoreErrors.ts
  packages/consumption/src/modules/requests/outgoing/OutgoingRequestsController.ts
  packages/consumption/test/modules/requests/OutgoingRequestsController.test.ts
Labels: bug

#279 Decrypting Messages fails when Relationship is not active anymore
  packages/transport/src/modules/messages/MessageController.ts
  packages/transport/test/modules/messages/MessageController.test.ts
Labels: bug

#281 Remove object loading by id and key
  packages/app-runtime/src/AppStringProcessor.ts
  packages/runtime/src/dataViews/transport/FileDVO.ts
  packages/runtime/src/extensibility/facades/anonymous/AnonymousTokensFacade.ts
  packages/runtime/src/types/transport/FileDTO.ts
  packages/runtime/src/types/transport/RelationshipTemplateDTO.ts
  packages/runtime/src/types/transport/TokenDTO.ts
  packages/runtime/src/useCases/anonymous/tokens/LoadPeerTokenAnonymous.ts
  packages/runtime/src/useCases/anonymous/tokens/LoadPeerTokenAnonymousByIdAndKey.ts
  packages/runtime/src/useCases/anonymous/tokens/index.ts
  packages/runtime/src/useCases/common/Schemas.ts
  packages/runtime/src/useCases/transport/files/FileMapper.ts
  packages/runtime/src/useCases/transport/files/GetOrLoadFile.ts
  packages/runtime/src/useCases/transport/relationshipTemplates/LoadPeerRelationshipTemplate.ts
  packages/runtime/src/useCases/transport/relationshipTemplates/RelationshipTemplateMapper.ts
  packages/runtime/src/useCases/transport/tokens/LoadPeerToken.ts
  packages/runtime/src/useCases/transport/tokens/TokenMapper.ts
  packages/runtime/test/anonymous/tokens.test.ts
  packages/runtime/test/transport/files.test.ts
Labels: breaking-change, refactoring
