Repository nmshd/runtime, pull requests merged in 2024-12, with the labels that each got.

#299 Process personalized and password protected objects in the StringProcessor
  .eslintrc
  packages/app-runtime/package.json
  packages/app-runtime/src/AppRuntime.ts
  packages/app-runtime/src/AppRuntimeErrors.ts
  packages/app-runtime/src/AppStringProcessor.ts
  packages/app-runtime/src/extensibility/ui/IUIBridge.ts
  packages/app-runtime/src/modules/appEvents/MailReceivedModule.ts
  packages/app-runtime/test/customMatchers.ts
  packages/app-runtime/test/lib/FakeUIBridge.ts
  packages/app-runtime/test/lib/MockEventBus.ts
  packages/app-runtime/test/lib/MockUIBridge.matchers.ts
  packages/app-runtime/test/lib/MockUIBridge.ts
  packages/app-runtime/test/lib/TestUtil.ts
  packages/app-runtime/test/lib/index.ts
  packages/app-runtime/test/runtime/AppStringProcessor.test.ts
  packages/runtime/src/useCases/common/Schemas.ts
  packages/runtime/src/useCases/transport/devices/CreateDeviceOnboardingToken.ts
  packages/runtime/test/lib/MockEventBus.ts
  packages/transport/src/core/Reference.ts
  packages/transport/src/core/types/PasswordProtection.ts
  packages/transport/src/core/types/PasswordProtectionCreationParameters.ts
  packages/transport/src/core/types/SharedPasswordProtection.ts
  packages/transport/test/modules/files/FileReference.test.ts
  packages/transport/test/modules/relationshipTemplates/RelationshipTemplateReference.test.ts
  packages/transport/test/modules/tokens/TokenContent.test.ts
  packages/transport/test/modules/tokens/TokenReference.test.ts
Labels: enhancement

#354 Simplify the PushNotificationModuleTest
  packages/app-runtime/test/lib/TestUtil.ts
  packages/app-runtime/test/lib/natives/FakeNativeBootstrapper.ts
  packages/app-runtime/test/modules/PushNotification.test.ts
Labels: test

#286 Block sending Messages to Identities which are in deletion or for which the Relationship is terminated
  packages/consumption/src/consumption/ConsumptionCoreErrors.ts
  packages/consumption/src/modules/requests/incoming/IncomingRequestsController.ts
  packages/consumption/src/modules/requests/outgoing/OutgoingRequestsController.ts
  packages/consumption/test/modules/requests/IncomingRequestsController.test.ts
  packages/consumption/test/modules/requests/OutgoingRequestsController.test.ts
  packages/consumption/test/modules/requests/RequestsIntegrationTest.ts
  packages/consumption/test/modules/requests/testHelpers/TestObjectFactory.ts
  packages/runtime/src/useCases/common/RuntimeErrors.ts
  packages/runtime/src/useCases/transport/messages/SendMessage.ts
  packages/runtime/test/lib/testUtils.ts
  packages/runtime/test/transport/messages.test.ts
  packages/runtime/test/transport/relationships.test.ts
  packages/transport/src/core/TransportCoreErrors.ts
  packages/transport/src/modules/messages/MessageController.ts
  packages/transport/test/modules/messages/MessageContent.test.ts
  packages/transport/test/modules/messages/MessageController.test.ts
  packages/transport/test/testHelpers/TestUtil.ts
Labels: enhancement

#357 Flaky queued Notifications test
  packages/runtime/test/transport/messages.test.ts
Labels: bug

#347 Simplify identity deletion process handling on second device by republishing events
  packages/app-runtime/src/AppConfig.ts
  packages/app-runtime/src/AppRuntime.ts
  packages/app-runtime/src/modules/runtimeEvents/DatawalletSynchronizedModule.ts
  packages/app-runtime/src/modules/runtimeEvents/IdentityDeletionProcessStatusChangedModule.ts
  packages/app-runtime/src/modules/runtimeEvents/index.ts
  packages/app-runtime/src/multiAccount/MultiAccountController.ts
  packages/app-runtime/test/lib/TestUtil.ts
  packages/app-runtime/test/modules/DatawalletSynchronizedModule.test.ts
  packages/app-runtime/test/modules/IdentityDeletionProcessStatusChangedModule.test.ts
  packages/app-runtime/test/runtime/AccountName.test.ts
  packages/app-runtime/test/runtime/TranslationProvider.test.ts
  packages/consumption/test/core/TestUtil.ts
  packages/runtime/src/events/EventProxy.ts
  packages/runtime/src/events/transport/IdentityDeletionProcessStatusChangedEvent.ts
  packages/runtime/test/transport/identityDeletionProcess.test.ts
  packages/transport/src/events/IdentityDeletionProcessStatusChangedEvent.ts
  packages/transport/src/modules/accounts/AccountController.ts
  packages/transport/src/modules/sync/ChangedItems.ts
  packages/transport/src/modules/sync/DatawalletModificationsProcessor.ts
  packages/transport/src/modules/sync/SyncController.ts
  packages/transport/test/modules/devices/DeviceOnboarding.test.ts
Labels: enhancement

#307 Provide backbone-defined valid tags for Attributes
  package-lock.json
  packages/consumption/src/modules/attributes/AttributesController.ts
  packages/consumption/src/modules/attributes/index.ts
  packages/consumption/src/modules/attributes/local/AttributeTagCollection.ts
  packages/consumption/test/modules/attributes/AttributeTagCollection.test.ts
  packages/runtime/src/extensibility/TransportServices.ts
  packages/runtime/src/extensibility/facades/consumption/AttributesFacade.ts
  packages/runtime/src/types/consumption/AttributeTagCollectionDTO.ts
  packages/runtime/src/types/consumption/index.ts
  packages/runtime/src/useCases/consumption/attributes/AttributeTagCollectionMapper.ts
  packages/runtime/src/useCases/consumption/attributes/GetAttributeTagCollection.ts
  packages/runtime/src/useCases/consumption/attributes/index.ts
  packages/runtime/test/consumption/attributeTagCollection.test.ts
  packages/transport/src/modules/index.ts
  packages/transport/src/modules/tags/backbone/BackboneGetTagCollection.ts
  packages/transport/src/modules/tags/backbone/TagClient.ts
Labels: enhancement

#358 Deletion of Relationship is proposed after peer deletion
  .dev/appsettings.override.json
  .dev/compose.backbone.env
  .dev/compose.backbone.yml
  package-lock.json
  packages/consumption/test/modules/requests/testHelpers/TestObjectFactory.ts
  packages/runtime/test/transport/messages.test.ts
  packages/transport/package.json
  packages/transport/src/modules/accounts/IdentityDeletionProcessController.ts
  packages/transport/src/modules/accounts/backbone/BackbonePostIdentityDeletionProcess.ts
  packages/transport/src/modules/accounts/backbone/IdentityDeletionProcessClient.ts
  packages/transport/test/modules/relationships/decomposition.test.ts
  packages/transport/test/testHelpers/TestUtil.ts
Labels: test

#361 Cannot create Relationship to deleted creator of RelationshipTemplate
  package-lock.json
  packages/transport/test/modules/relationships/RelationshipsController.test.ts
  packages/transport/test/testHelpers/TestUtil.ts
Labels: test

#360 Cleanup AccountController and Clients
  packages/transport/src/modules/accounts/AccountController.ts
  packages/transport/src/modules/devices/backbone/DeviceAuthClient.ts
  packages/transport/src/modules/devices/backbone/DeviceClient.ts
  packages/transport/src/modules/index.ts
Labels: refactoring

#364 Update release config
  .github/release.yml
Labels: chore

#365 Make identity deletion job configurable
  packages/transport/test/testHelpers/TestUtil.ts
Labels: test

#363 Identity Recovery Kits
  .dev/appsettings.override.json
  .dev/compose.backbone.env
  .dev/compose.backbone.yml
  packages/app-runtime/test/runtime/Onboarding.test.ts
  packages/runtime/src/extensibility/TransportServices.ts
  packages/runtime/src/extensibility/facades/transport/IdentityRecoveryKitsFacade.ts
  packages/runtime/src/extensibility/facades/transport/index.ts
  packages/runtime/src/types/transport/DeviceDTO.ts
  packages/runtime/src/useCases/common/RuntimeErrors.ts
  packages/runtime/src/useCases/common/Schemas.ts
  packages/runtime/src/useCases/transport/devices/DeviceMapper.ts
  packages/runtime/src/useCases/transport/identityRecoveryKits/CheckForExistingIdentityRecoveryKit.ts
  packages/runtime/src/useCases/transport/identityRecoveryKits/CreateIdentityRecoveryKit.ts
  packages/runtime/src/useCases/transport/identityRecoveryKits/index.ts
  packages/runtime/src/useCases/transport/index.ts
  packages/runtime/test/transport/identityRecoveryKits.test.ts
  packages/transport/src/modules/accounts/AccountController.ts
  packages/transport/src/modules/accounts/backbone/IdentityClient.ts
  packages/transport/src/modules/devices/DevicesController.ts
  packages/transport/src/modules/devices/backbone/BackbonePostDevices.ts
  packages/transport/src/modules/devices/local/Device.ts
  packages/transport/src/modules/devices/local/SendDeviceParameters.ts
  packages/transport/src/modules/tokens/TokenController.ts
Labels: enhancement

#366 Add Runtime error for attempt to establish Relationships to deleted Identities
  packages/runtime/test/transport/relationships.test.ts
  packages/transport/src/core/TransportCoreErrors.ts
  packages/transport/src/modules/relationships/RelationshipsController.ts
  packages/transport/test/modules/relationships/RelationshipsController.test.ts
Labels: enhancement

#362 Query Tokens for password protection
  packages/runtime/src/useCases/common/Schemas.ts
  packages/runtime/src/useCases/transport/tokens/GetTokens.ts
  packages/runtime/test/transport/tokens.test.ts
Labels: enhancement

#356 Delete obsolete LocalAccounts on App startup
  packages/app-runtime/src/AppRuntime.ts
  packages/app-runtime/src/multiAccount/AccountServices.ts
  packages/app-runtime/src/multiAccount/MultiAccountController.ts
  packages/app-runtime/test/lib/TestUtil.ts
  packages/app-runtime/test/runtime/Offboarding.test.ts
  packages/app-runtime/test/runtime/Startup.test.ts
  packages/runtime/src/extensibility/facades/transport/AccountFacade.ts
  packages/runtime/src/useCases/transport/account/CheckIfIdentityIsDeleted.ts
  packages/runtime/src/useCases/transport/account/index.ts
  packages/runtime/test/transport/account.test.ts
  packages/transport/src/modules/accounts/IdentityController.ts
  packages/transport/src/modules/accounts/backbone/BackboneCheckIfIdentityIsDeleted.ts
  packages/transport/src/modules/accounts/backbone/IdentityClient.ts
  packages/transport/test/modules/account/IdentityController.test.ts
Labels: enhancement

#368 Expose setting the length of the grace period when initiating an IdentityDeletionProcess
  packages/app-runtime/test/runtime/Startup.test.ts
  packages/runtime/src/extensibility/facades/transport/IdentityDeletionProcessesFacade.ts
  packages/runtime/src/useCases/common/Schemas.ts
  packages/runtime/src/useCases/transport/identityDeletionProcesses/InitiateIdentityDeletionProcess.ts
  packages/runtime/test/transport/account.test.ts
Labels: enhancement

#371 DateTime from DateTime does not return the same date
  packages/core-types/src/CoreDate.ts
  packages/core-types/test/CoreDate.test.ts
Labels: bug

#319 Uniqueness of `key` for RelationshipAttributes
  packages/consumption/src/consumption/ConsumptionCoreErrors.ts
  packages/consumption/src/modules/attributes/AttributesController.ts
  packages/consumption/src/modules/requests/incoming/IncomingRequestsController.ts
  packages/consumption/src/modules/requests/itemProcessors/createAttribute/CreateAttributeRequestItemProcessor.ts
  packages/consumption/src/modules/requests/itemProcessors/proposeAttribute/ProposeAttributeRequestItemProcessor.ts
  packages/consumption/src/modules/requests/itemProcessors/readAttribute/ReadAttributeRequestItemProcessor.ts
  packages/consumption/src/modules/requests/outgoing/OutgoingRequestsController.ts
  packages/consumption/src/modules/requests/utility/validateRelationshipAttributesWithinRequest.ts
  packages/consumption/test/modules/attributes/AttributesController.test.ts
  packages/consumption/test/modules/requests/IncomingRequestsController.test.ts
  packages/consumption/test/modules/requests/OutgoingRequestsController.test.ts
  packages/consumption/test/modules/requests/RequestsIntegrationTest.ts
  packages/consumption/test/modules/requests/itemProcessors/createAttribute/Context.ts
  packages/consumption/test/modules/requests/itemProcessors/createAttribute/CreateAttributeRequestItemProcessor.test.ts
  packages/consumption/test/modules/requests/itemProcessors/proposeAttribute/ProposeAttributeRequestItemProcessor.test.ts
  packages/consumption/test/modules/requests/itemProcessors/readAttribute/ReadAttributeRequestItemProcessor.test.ts
  packages/runtime/test/consumption/attributes.test.ts
  packages/runtime/test/dataViews/requestItems/CreateRelationshipAttributeRequestItemDVO.test.ts
  packages/runtime/test/transport/messages.test.ts
Labels: enhancement

#373 Rename getDeviceOnboardingToken to createDeviceOnboardingToken
  packages/app-runtime/test/runtime/AppStringProcessor.test.ts
  packages/runtime/src/extensibility/facades/transport/DevicesFacade.ts
  packages/runtime/test/transport/account.test.ts
Labels: refactoring

#369 Request can be created and sent via a message with an expiration date that has passed
  packages/consumption/src/consumption/ConsumptionCoreErrors.ts
  packages/consumption/src/modules/requests/outgoing/OutgoingRequestsController.ts
  packages/consumption/test/modules/requests/OutgoingRequestsController.test.ts
  packages/runtime/src/useCases/common/RuntimeErrors.ts
  packages/runtime/src/useCases/transport/messages/SendMessage.ts
  packages/runtime/test/transport/messages.test.ts
Labels: bug

#375 Add PasswordProtectionDTO
  packages/runtime/src/dataViews/consumption/PeerRelationshipTemplateDVO.ts
  packages/runtime/src/dataViews/transport/RelationshipTemplateDVO.ts
  packages/runtime/src/types/transport/PasswordProtectionDTO.ts
  packages/runtime/src/types/transport/RelationshipTemplateDTO.ts
  packages/runtime/src/types/transport/TokenDTO.ts
  packages/runtime/src/types/transport/index.ts
Labels: refactoring

#376 Add debug log for SynchronizedCollection in CI runs for database writes with outdated data
  packages/transport/src/modules/sync/SynchronizedCollection.ts
Labels: chore
