Repository nmshd/runtime, pull requests merged in 2024-10, with the labels that each got.

#288 Unstable tests
  packages/runtime/test/transport/identityDeletionPeerProcessing.test.ts
Labels: chore

#284 Extend Truncated References
  packages/transport/src/core/Reference.ts
  packages/transport/src/core/Transport.ts
  packages/transport/src/core/TransportCoreErrors.ts
  packages/transport/test/modules/files/FileReference.test.ts
  packages/transport/test/modules/relationshipTemplates/RelationshipTemplateReference.test.ts
  packages/transport/test/modules/tokens/TokenReference.test.ts
Labels: enhancement

#249 Personalized Tokens
  .dev/compose.backbone.env
  packages/runtime/src/types/transport/TokenDTO.ts
  packages/runtime/src/useCases/common/Schemas.ts
  packages/runtime/src/useCases/transport/files/CreateTokenForFile.ts
  packages/runtime/src/useCases/transport/files/CreateTokenQRCodeForFile.ts
  packages/runtime/src/useCases/transport/relationshipTemplates/CreateTokenForOwnRelationshipTemplate.ts
  packages/runtime/src/useCases/transport/relationshipTemplates/CreateTokenQRCodeForOwnRelationshipTemplate.ts
  packages/runtime/src/useCases/transport/tokens/CreateOwnToken.ts
  packages/runtime/src/useCases/transport/tokens/TokenMapper.ts
  packages/runtime/test/anonymous/tokens.test.ts
  packages/runtime/test/lib/testUtils.ts
  packages/runtime/test/transport/tokens.test.ts
  packages/transport/src/core/TransportCoreErrors.ts
  packages/transport/src/modules/tokens/AnonymousTokenController.ts
  packages/transport/src/modules/tokens/TokenController.ts
  packages/transport/src/modules/tokens/backbone/BackboneGetTokens.ts
  packages/transport/src/modules/tokens/backbone/BackbonePostTokens.ts
  packages/transport/src/modules/tokens/local/CachedToken.ts
  packages/transport/src/modules/tokens/local/SendTokenParameters.ts
  packages/transport/src/modules/tokens/local/Token.ts
  packages/transport/test/modules/PublicAPI.test.ts
  packages/transport/test/modules/tokens/AnonymousTokenController.test.ts
  packages/transport/test/modules/tokens/TokenController.test.ts
Labels: enhancement

#278 Datawallet modifications are not executed in the right order and wrong objects are deleted
  packages/transport/src/modules/sync/DatawalletModificationsProcessor.ts
  packages/transport/test/modules/sync/SyncController.ordered.test.ts
  packages/transport/test/testHelpers/TestUtil.ts
Labels: bug

#289 ShareAttributeRequestItemDVOs `attribute.id` is overridden with with `undefined`
  packages/runtime/src/dataViews/DataViewExpander.ts
Labels: bug

#292 Remove relationshipRequest naming
  packages/app-runtime/test/lib/TestUtil.ts
  packages/transport/src/modules/relationships/RelationshipsController.ts
Labels: refactoring

#290 Add `deletionDate` to relationship's deletion info
  package-lock.json
  package.json
  packages/runtime/src/dataViews/DataViewExpander.ts
  packages/runtime/src/dataViews/transport/RelationshipDVO.ts
  packages/runtime/src/types/transport/RelationshipDTO.ts
  packages/runtime/test/transport/identityDeletionPeerProcessing.test.ts
  packages/transport/src/modules/relationships/local/PeerDeletionInfo.ts
  packages/transport/src/modules/sync/externalEventProcessors/PeerDeletedExternalEventProcessor.ts
  packages/transport/src/modules/sync/externalEventProcessors/PeerToBeDeletedExternalEventProcessor.ts
  packages/transport/test/modules/relationships/PeerDeletionInfo.test.ts
  packages/transport/test/modules/sync/externalEventProcessors/PeerDeletedExternalEventProcessor.test.ts
  packages/transport/test/modules/sync/externalEventProcessors/PeerToBeDeletedExternalEventProcessor.test.ts
Labels: enhancement

#293 Upgrade the `form-data` lib
  package-lock.json
  package.json
  packages/consumption/src/modules/requests/itemProcessors/utility/validateAttributeMatchesWithQuery.ts
  packages/transport/package.json
  packages/transport/src/core/CoreCrypto.ts
  packages/transport/src/core/Reference.ts
  packages/transport/src/core/TransportCoreErrors.ts
  packages/transport/src/core/backbone/RESTClient.ts
  packages/transport/src/modules/accounts/IdentityDeletionProcessController.ts
  packages/transport/src/modules/sync/DatawalletModificationsProcessor.ts
  packages/transport/src/modules/tokens/TokenController.ts
  packages/transport/test/core/backbone/Paginator.test.ts
  packages/transport/test/modules/PublicAPI.test.ts
  packages/transport/test/modules/relationships/RelationshipsController.test.ts
  packages/transport/test/testHelpers/FakeSyncClient.ts
  packages/transport/test/utils/Random.test.ts
  packages/transport/test/utils/Reflection.test.ts
Labels: bug

#294 Improve address regex
  packages/runtime/src/useCases/common/Schemas.ts
  packages/runtime/src/useCases/common/validation/ValidatableStrings.ts
  packages/runtime/test/consumption/attributes.test.ts
Labels: enhancement

#270 Personalized RelationshipTemplates
  packages/runtime/src/dataViews/consumption/PeerRelationshipTemplateDVO.ts
  packages/runtime/src/dataViews/transport/RelationshipTemplateDVO.ts
  packages/runtime/src/types/transport/RelationshipTemplateDTO.ts
  packages/runtime/src/useCases/common/RuntimeErrors.ts
  packages/runtime/src/useCases/common/Schemas.ts
  packages/runtime/src/useCases/transport/account/LoadItemFromTruncatedReference.ts
  packages/runtime/src/useCases/transport/relationshipTemplates/CreateOwnRelationshipTemplate.ts
  packages/runtime/src/useCases/transport/relationshipTemplates/CreateTokenForOwnRelationshipTemplate.ts
  packages/runtime/src/useCases/transport/relationshipTemplates/CreateTokenQRCodeForOwnRelationshipTemplate.ts
  packages/runtime/src/useCases/transport/relationshipTemplates/LoadPeerRelationshipTemplate.ts
  packages/runtime/src/useCases/transport/relationshipTemplates/RelationshipTemplateMapper.ts
  packages/runtime/test/dataViews/RelationshipTemplateDVO.test.ts
  packages/runtime/test/transport/relationshipTemplates.test.ts
  packages/transport/src/modules/relationshipTemplates/RelationshipTemplateController.ts
  packages/transport/src/modules/relationshipTemplates/backbone/BackboneGetRelationshipTemplates.ts
  packages/transport/src/modules/relationshipTemplates/backbone/BackbonePostRelationshipTemplates.ts
  packages/transport/src/modules/relationshipTemplates/local/CachedRelationshipTemplate.ts
  packages/transport/src/modules/relationshipTemplates/local/RelationshipTemplate.ts
  packages/transport/src/modules/relationshipTemplates/local/SendRelationshipTemplateParameters.ts
  packages/transport/src/modules/tokens/transmission/TokenContentRelationshipTemplate.ts
  packages/transport/test/modules/relationshipTemplates/RelationshipTemplateController.test.ts
  packages/transport/test/modules/tokens/TokenContent.test.ts
  packages/transport/test/modules/tokens/TokenController.test.ts
Labels: enhancement

#297 Make addressGenerationHostnameOverride configurable for tests
  packages/app-runtime/test/lib/TestUtil.ts
  packages/consumption/test/core/TestUtil.ts
  packages/runtime/test/lib/RuntimeServiceProvider.ts
  packages/transport/test/testHelpers/TestUtil.ts
Labels: chore, test

#269 Extend DeciderModule to automatically decide Requests
  packages/app-runtime/src/modules/appEvents/RelationshipTemplateProcessedModule.ts
  packages/runtime/src/RuntimeConfig.ts
  packages/runtime/src/events/consumption/MessageProcessedEvent.ts
  packages/runtime/src/events/consumption/RelationshipTemplateProcessedEvent.ts
  packages/runtime/src/modules/DeciderModule.ts
  packages/runtime/src/modules/decide/RequestConfig.ts
  packages/runtime/src/modules/decide/ResponseConfig.ts
  packages/runtime/src/modules/decide/index.ts
  packages/runtime/src/useCases/common/RuntimeErrors.ts
  packages/runtime/src/useCases/common/Schemas.ts
  packages/runtime/test/lib/RuntimeServiceProvider.ts
  packages/runtime/test/modules/DeciderModule.test.ts
  packages/runtime/test/modules/DeciderModule.unit.test.ts
Labels: enhancement

#302 Feature/Add check for undefined `parentId` of shared Attributes
  packages/consumption/src/modules/attributes/local/LocalAttribute.ts
Labels: enhancement

#282 Add `thirdPartyAddress` to the Attribute's `shareInfo`
  packages/consumption/src/modules/attributes/AttributesController.ts
  packages/consumption/src/modules/attributes/local/CreateSharedLocalAttributeParams.ts
  packages/consumption/src/modules/attributes/local/LocalAttribute.ts
  packages/consumption/src/modules/attributes/local/LocalAttributeShareInfo.ts
  packages/consumption/src/modules/requests/itemProcessors/readAttribute/ReadAttributeRequestItemProcessor.ts
  packages/consumption/src/modules/requests/itemProcessors/shareAttribute/ShareAttributeRequestItemProcessor.ts
  packages/consumption/test/modules/attributes/AttributesController.test.ts
  packages/consumption/test/modules/attributes/LocalAttributeShareInfo.test.ts
  packages/consumption/test/modules/requests/itemProcessors/readAttribute/ReadAttributeRequestItemProcessor.test.ts
  packages/consumption/test/modules/requests/itemProcessors/shareAttribute/ShareAttributeRequestItemProcessor.test.ts
  packages/content/src/requests/items/readAttribute/ReadAttributeAcceptResponseItem.ts
  packages/content/src/requests/items/shareAttribute/ShareAttributeRequestItem.ts
  packages/runtime/src/dataViews/DataViewExpander.ts
  packages/runtime/src/dataViews/consumption/DecidableRequestItemDVOs.ts
  packages/runtime/src/dataViews/consumption/LocalAttributeDVO.ts
  packages/runtime/src/dataViews/content/RequestItemDVOs.ts
  packages/runtime/src/dataViews/content/ResponseItemDVOs.ts
  packages/runtime/src/modules/AttributeListenerModule.ts
  packages/runtime/src/types/consumption/LocalAttributeDTO.ts
  packages/runtime/src/useCases/consumption/attributes/GetAttributes.ts
  packages/runtime/src/useCases/consumption/attributes/GetOwnSharedAttributes.ts
  packages/runtime/src/useCases/consumption/attributes/GetPeerSharedAttributes.ts
  packages/runtime/test/consumption/attributes.test.ts
  packages/runtime/test/lib/testUtils.ts
  packages/runtime/test/modules/RequestModule.test.ts
Labels: enhancement

#303 Build schemas
  packages/runtime/src/useCases/common/Schemas.ts
Labels: chore

#212 Add CanCreateRelationshipUseCase and handling of expired RelationshipTemplates
  .dev/compose.backbone.env
  packages/consumption/src/consumption/ConsumptionController.ts
  packages/consumption/src/modules/requests/incoming/IncomingRequestsController.ts
  packages/consumption/src/modules/requests/local/LocalRequest.ts
  packages/consumption/test/modules/requests/IncomingRequestsController.test.ts
  packages/consumption/test/modules/requests/RequestsIntegrationTest.ts
  packages/consumption/test/modules/requests/local/LocalRequest.test.ts
  packages/consumption/test/modules/requests/testHelpers/TestObjectFactory.ts
  packages/core-types/src/CoreDate.ts
  packages/runtime/src/extensibility/facades/transport/RelationshipsFacade.ts
  packages/runtime/src/useCases/common/RuntimeErrors.ts
  packages/runtime/src/useCases/transport/relationshipTemplates/CreateOwnRelationshipTemplate.ts
  packages/runtime/src/useCases/transport/relationships/CanCreateRelationship.ts
  packages/runtime/src/useCases/transport/relationships/CreateRelationship.ts
  packages/runtime/test/consumption/requests.test.ts
  packages/runtime/test/lib/testUtils.ts
  packages/runtime/test/lib/testUtilsWithInactiveModules.ts
  packages/runtime/test/modules/DeciderModule.test.ts
  packages/runtime/test/transport/relationshipTemplates.test.ts
  packages/runtime/test/transport/relationships.test.ts
  packages/transport/src/core/TransportCoreErrors.ts
  packages/transport/src/modules/relationshipTemplates/local/RelationshipTemplate.ts
  packages/transport/src/modules/relationships/RelationshipsController.ts
  packages/transport/src/modules/relationships/backbone/BackboneCanCreateRelationship.ts
  packages/transport/src/modules/relationships/backbone/RelationshipClient.ts
  packages/transport/test/modules/PublicAPI.test.ts
Labels: bug, enhancement

#308 Downgrade Node.js
  .github/workflows/publish.yml
  .github/workflows/test.yml
Labels: ci

#312 Remove unused Template resolver from IncomingRequestsController
  packages/consumption/src/consumption/ConsumptionController.ts
  packages/consumption/src/modules/requests/incoming/IncomingRequestsController.ts
  packages/consumption/test/modules/requests/IncomingRequestsController.test.ts
  packages/consumption/test/modules/requests/RequestsIntegrationTest.ts
Labels: refactoring

#310 Remove circular dependency
  .ci/runChecks.sh
  packages/runtime/src/modules/DeciderModule.ts
  packages/runtime/src/useCases/consumption/attributes/GetRepositoryAttributes.ts
Labels: chore

#311 Remove mentions of IdentityDeletionProcessChangedEvent
  packages/runtime/src/modules/RequestModule.ts
  packages/transport/src/modules/sync/externalEventProcessors/ExternalEventProcessorRegistry.ts
  packages/transport/src/modules/sync/externalEventProcessors/IdentityDeletionProcessStatusChangedExternalEventProcessor.ts
Labels: refactoring

#313 Allow filtering by personalization
  packages/runtime/src/useCases/common/Schemas.ts
  packages/runtime/src/useCases/transport/relationshipTemplates/GetRelationshipTemplates.ts
  packages/runtime/src/useCases/transport/tokens/GetTokens.ts
  packages/runtime/test/transport/relationshipTemplates.test.ts
  packages/runtime/test/transport/tokens.test.ts
Labels: enhancement

#306 Upgrade crypto library
  package-lock.json
  package.json
  packages/consumption/package.json
  packages/runtime/package.json
  packages/transport/package.json
  packages/transport/src/core/CoreCrypto.ts
Labels: refactoring

#316 Update GmbH to AG
  LICENSE
  package.json
  packages/app-runtime/LICENSE
  packages/app-runtime/package.json
  packages/consumption/LICENSE
  packages/consumption/package.json
  packages/content/LICENSE
  packages/content/package.json
  packages/content/test/attributes/IdentityAttribute.test.ts
  packages/core-types/LICENSE
  packages/core-types/package.json
  packages/runtime/LICENSE
  packages/runtime/package.json
  packages/transport/LICENSE
  packages/transport/package.json
Labels: chore

#317 Refine IdentityMetadata tests
  packages/runtime/test/consumption/identityMetadata.test.ts
Labels: chore
