Repository nmshd/runtime, pull requests merged in 2024-11, with the labels that each got.

#318 Update README_dev
  README_dev.md
Labels: chore

#320 Bump Node.js version in pipelines
  .github/workflows/publish.yml
  .github/workflows/test.yml
Labels: ci

#322 DataViewExpander is erroring for normal behavior of the RequestModule
  packages/runtime/src/dataViews/DataViewExpander.ts
  packages/runtime/src/dataViews/content/MessageDVOs.ts
  packages/runtime/src/dataViews/content/index.ts
Labels: bug

#323 Make `creationContent` parameter of CanCreateRelationshipUseCase optional
  packages/runtime/src/extensibility/facades/transport/RelationshipsFacade.ts
  packages/runtime/src/useCases/common/Schemas.ts
  packages/runtime/src/useCases/transport/relationships/CanCreateRelationship.ts
  packages/runtime/src/useCases/transport/relationships/index.ts
  packages/runtime/test/transport/relationships.test.ts
Labels: enhancement

#324 Re-generate schemas
  packages/runtime/src/useCases/common/Schemas.ts
Labels: chore

#326 Check runtime schemas
  .ci/checkGitDiff.sh
  .github/workflows/check-schema.yml
Labels: ci

#327 Refine test payloads
  packages/consumption/test/modules/attributeListeners/AttributeListenersController.test.ts
  packages/consumption/test/modules/attributes/AttributesController.test.ts
  packages/consumption/test/modules/requests/itemProcessors/proposeAttribute/ProposeAttributeRequestItemProcessor.test.ts
  packages/consumption/test/modules/requests/itemProcessors/readAttribute/ReadAttributeRequestItemProcessor.test.ts
  packages/consumption/test/modules/requests/itemProcessors/registerAttributeListener/RegisterAttributeListenerRequestItemProcessor.test.ts
  packages/consumption/test/modules/requests/itemProcessors/shareAttribute/ShareAttributeRequestItemProcessor.test.ts
  packages/consumption/test/modules/requests/itemProcessors/utility/validateAttributeMatchesWithQuery.test.ts
  packages/consumption/test/modules/requests/testHelpers/TestObjectFactory.ts
  packages/content/test/attributes/IQLQuery.test.ts
  packages/content/test/attributes/RelationshipAttribute.test.ts
  packages/content/test/requests/items/ProposeAttributeRequestItem.test.ts
  packages/runtime/test/consumption/attributes.test.ts
  packages/runtime/test/consumption/iqlQuery.test.ts
  packages/runtime/test/dataViews/MessageDVO.test.ts
  packages/runtime/test/dataViews/RelationshipDVO.test.ts
  packages/runtime/test/dataViews/RelationshipTemplateDVO.test.ts
  packages/runtime/test/lib/testUtils.ts
  packages/runtime/test/modules/AttributeListenerModule.test.ts
  packages/runtime/test/modules/RequestModule.test.ts
  packages/runtime/test/transport/tokens.test.ts
Labels: chore

#328 Fix flaky test
  packages/runtime/test/modules/RequestModule.test.ts
Labels: test

#330 Support Relationship Decomposition Based Identity Deletion
  packages/runtime/src/types/transport/RelationshipDTO.ts
  packages/runtime/src/useCases/transport/relationships/RelationshipMapper.ts
  packages/transport/src/modules/relationships/local/RelationshipAuditLog.ts
  packages/transport/src/modules/relationships/local/RelationshipAuditLogEntry.ts
  packages/transport/src/modules/relationships/transmission/RelationshipAuditLog.ts
Labels: enhancement

#331 Extend PR readiness checklist by self-review checkbox
  .github/PULL_REQUEST_TEMPLATE.md
Labels: chore

#337 Attributes can be succeeded without changing their content
  packages/consumption/src/consumption/ConsumptionCoreErrors.ts
  packages/consumption/src/modules/attributes/AttributesController.ts
  packages/consumption/test/modules/attributes/AttributesController.test.ts
  packages/consumption/test/modules/requests/itemProcessors/proposeAttribute/ProposeAttributeRequestItemProcessor.test.ts
  packages/consumption/test/modules/requests/itemProcessors/readAttribute/ReadAttributeRequestItemProcessor.test.ts
  packages/consumption/test/modules/requests/testHelpers/TestObjectFactory.ts
Labels: bug

#339 Fix flaky test
  packages/consumption/test/modules/requests/IncomingRequestsController.test.ts
Labels: chore

#295 Password-protected RelationshipTemplates
  .dev/compose.backbone.env
  packages/consumption/test/core/TestUtil.ts
  packages/consumption/test/modules/requests/RequestEnd2End.test.ts
  packages/runtime/src/dataViews/consumption/PeerRelationshipTemplateDVO.ts
  packages/runtime/src/dataViews/transport/RelationshipTemplateDVO.ts
  packages/runtime/src/types/transport/RelationshipTemplateDTO.ts
  packages/runtime/src/useCases/common/RuntimeErrors.ts
  packages/runtime/src/useCases/common/Schemas.ts
  packages/runtime/src/useCases/transport/account/LoadItemFromTruncatedReference.ts
  packages/runtime/src/useCases/transport/relationshipTemplates/CreateOwnRelationshipTemplate.ts
  packages/runtime/src/useCases/transport/relationshipTemplates/CreateTokenForOwnRelationshipTemplate.ts
  packages/runtime/src/useCases/transport/relationshipTemplates/CreateTokenQRCodeForOwnRelationshipTemplate.ts
  packages/runtime/src/useCases/transport/relationshipTemplates/LoadPeerRelationshipTemplate.ts
  packages/runtime/src/useCases/transport/relationshipTemplates/RelationshipTemplateMapper.ts
  packages/runtime/test/dataViews/RelationshipTemplateDVO.test.ts
  packages/runtime/test/transport/relationshipTemplates.test.ts
  packages/transport/src/core/Reference.ts
  packages/transport/src/core/TransportCoreErrors.ts
  packages/transport/src/core/types/PasswordProtection.ts
  packages/transport/src/core/types/PasswordProtectionCreationParameters.ts
  packages/transport/src/core/types/SharedPasswordProtection.ts
  packages/transport/src/core/types/index.ts
  packages/transport/src/modules/relationshipTemplates/RelationshipTemplateController.ts
  packages/transport/src/modules/relationshipTemplates/backbone/BackboneGetRelationshipTemplates.ts
  packages/transport/src/modules/relationshipTemplates/backbone/BackbonePostRelationshipTemplates.ts
  packages/transport/src/modules/relationshipTemplates/backbone/RelationshipTemplateClient.ts
  packages/transport/src/modules/relationshipTemplates/local/RelationshipTemplate.ts
  packages/transport/src/modules/relationshipTemplates/local/SendRelationshipTemplateParameters.ts
  packages/transport/src/modules/tokens/transmission/TokenContentRelationshipTemplate.ts
  packages/transport/test/end2end/End2End.test.ts
  packages/transport/test/modules/files/FileReference.test.ts
  packages/transport/test/modules/relationshipTemplates/RelationshipTemplateController.test.ts
  packages/transport/test/modules/relationshipTemplates/RelationshipTemplateReference.test.ts
  packages/transport/test/modules/sync/SyncController.error.test.ts
  packages/transport/test/modules/sync/SyncController.relationships.test.ts
  packages/transport/test/modules/tokens/TokenContent.test.ts
  packages/transport/test/modules/tokens/TokenController.test.ts
  packages/transport/test/modules/tokens/TokenReference.test.ts
  packages/transport/test/testHelpers/TestUtil.ts
Labels: enhancement

#341 Don't compare classes with `_.isEqual`
  packages/consumption/src/modules/attributes/AttributesController.ts
Labels: refactoring

#343 Remove unused injected controller
  packages/runtime/src/useCases/transport/relationships/CreateRelationship.ts
Labels: chore

#342 Allow passing no title and description when uploading a file
  packages/runtime/src/useCases/common/Schemas.ts
  packages/runtime/src/useCases/transport/files/UploadOwnFile.ts
  packages/transport/src/modules/files/local/SendFileParameters.ts
Labels: enhancement

#344 Upgrade Backbone Version
  .dev/appsettings.override.json
  .dev/compose.backbone.env
  packages/transport/test/modules/relationshipTemplates/RelationshipTemplateController.test.ts
Labels: chore

#345 Add `deletionDate` to LocalAccount
  packages/app-runtime/src/AppConfig.ts
  packages/app-runtime/src/AppRuntime.ts
  packages/app-runtime/src/events/DatawalletSynchronizedEvent.ts
  packages/app-runtime/src/events/LocalAccountDeletionDateChangedEvent.ts
  packages/app-runtime/src/events/index.ts
  packages/app-runtime/src/modules/pushNotifications/PushNotificationModule.ts
  packages/app-runtime/src/modules/runtimeEvents/DatawalletSynchronizedModule.ts
  packages/app-runtime/src/modules/runtimeEvents/IdentityDeletionProcessStatusChangedModule.ts
  packages/app-runtime/src/modules/runtimeEvents/index.ts
  packages/app-runtime/src/multiAccount/MultiAccountController.ts
  packages/app-runtime/src/multiAccount/data/LocalAccount.ts
  packages/app-runtime/src/multiAccount/data/LocalAccountDTO.ts
  packages/app-runtime/src/multiAccount/data/LocalAccountMapper.ts
  packages/app-runtime/test/modules/DatawalletSynchronizedModule.test.ts
  packages/app-runtime/test/modules/IdentityDeletionProcessStatusChangedModule.test.ts
  packages/app-runtime/test/modules/PushNotification.test.ts
  packages/app-runtime/test/multiAccount/MultiAccountController.test.ts
  packages/runtime/src/events/EventProxy.ts
  packages/runtime/src/events/transport/DatawalletSynchronizedEvent.ts
  packages/runtime/src/events/transport/index.ts
  packages/runtime/test/transport/account.test.ts
  packages/transport/src/events/DatawalletSynchronizedEvent.ts
  packages/transport/src/events/index.ts
  packages/transport/src/modules/accounts/AccountController.ts
  packages/transport/src/modules/sync/SyncController.ts
Labels: enhancement

#349 Configure GitHub repo using settings file
  .github/settings.yaml
Labels: chore

#350 Change settings file ending
  .github/settings.yml
Labels: chore

#351 Fix flaky Test
  packages/transport/test/utils/IdentityGenerator.test.ts
Labels: test

#300 Password-protected Tokens
  .dev/compose.backbone.env
  packages/runtime/src/types/transport/TokenDTO.ts
  packages/runtime/src/useCases/anonymous/tokens/LoadPeerTokenAnonymous.ts
  packages/runtime/src/useCases/common/RuntimeErrors.ts
  packages/runtime/src/useCases/common/Schemas.ts
  packages/runtime/src/useCases/common/index.ts
  packages/runtime/src/useCases/common/validation/TokenAndTemplateCreationValidator.ts
  packages/runtime/src/useCases/transport/account/LoadItemFromTruncatedReference.ts
  packages/runtime/src/useCases/transport/files/CreateTokenForFile.ts
  packages/runtime/src/useCases/transport/files/CreateTokenQRCodeForFile.ts
  packages/runtime/src/useCases/transport/files/GetOrLoadFile.ts
  packages/runtime/src/useCases/transport/relationshipTemplates/CreateOwnRelationshipTemplate.ts
  packages/runtime/src/useCases/transport/relationshipTemplates/CreateTokenForOwnRelationshipTemplate.ts
  packages/runtime/src/useCases/transport/relationshipTemplates/CreateTokenQRCodeForOwnRelationshipTemplate.ts
  packages/runtime/src/useCases/transport/relationshipTemplates/LoadPeerRelationshipTemplate.ts
  packages/runtime/src/useCases/transport/tokens/CreateOwnToken.ts
  packages/runtime/src/useCases/transport/tokens/LoadPeerToken.ts
  packages/runtime/src/useCases/transport/tokens/TokenMapper.ts
  packages/runtime/test/anonymous/tokens.test.ts
  packages/runtime/test/lib/testUtils.ts
  packages/runtime/test/transport/passwordProtection/files.test.ts
  packages/runtime/test/transport/passwordProtection/relationshipTemplates.test.ts
  packages/runtime/test/transport/passwordProtection/tokens.test.ts
  packages/runtime/test/transport/relationshipTemplates.test.ts
  packages/transport/src/core/types/PasswordProtection.ts
  packages/transport/src/modules/tokens/AnonymousTokenController.ts
  packages/transport/src/modules/tokens/TokenController.ts
  packages/transport/src/modules/tokens/backbone/AnonymousTokenClient.ts
  packages/transport/src/modules/tokens/backbone/BackboneGetTokens.ts
  packages/transport/src/modules/tokens/backbone/BackbonePostTokens.ts
  packages/transport/src/modules/tokens/backbone/TokenClient.ts
  packages/transport/src/modules/tokens/local/SendTokenParameters.ts
  packages/transport/src/modules/tokens/local/Token.ts
  packages/transport/test/modules/tokens/AnonymousTokenController.test.ts
  packages/transport/test/modules/tokens/TokenController.test.ts
Labels: enhancement
