Repository nmshd/runtime, pull requests merged in 2025-07, with the labels that each got.

#633 Endless loop when updating request expiry
  packages/consumption/src/modules/requests/incoming/IncomingRequestsController.ts
  packages/consumption/src/modules/requests/outgoing/OutgoingRequestsController.ts
Labels: bug

#641 Update lint script
  packages/runtime-types/package.json
Labels: chore

#631 Fix flaky tests
  packages/consumption/test/core/TestUtil.ts
  packages/consumption/test/modules/requests/itemProcessors/transferFileOwnership/TransferFileOwnershipRequestItemProcessor.test.ts
  packages/runtime/test/lib/testUtils.ts
  packages/runtime/test/transport/relationships.test.ts
  packages/transport/test/modules/messages/MessageController.test.ts
  packages/transport/test/modules/sync/SyncController.relationships.test.ts
  packages/transport/test/testHelpers/TestUtil.ts
Labels: test

#642 Remove AttributeListeners
  packages/app-runtime/src/AppConfig.ts
  packages/consumption/src/consumption/ConsumptionController.ts
  packages/consumption/src/consumption/ConsumptionControllerName.ts
  packages/consumption/src/consumption/ConsumptionIds.ts
  packages/consumption/src/modules/attributeListeners/AttributeListenersController.ts
  packages/consumption/src/modules/attributeListeners/events/AttributeListenerCreatedEvent.ts
  packages/consumption/src/modules/attributeListeners/events/index.ts
  packages/consumption/src/modules/attributeListeners/index.ts
  packages/consumption/src/modules/attributeListeners/local/CreateLocalAttributeListenerParams.ts
  packages/consumption/src/modules/attributeListeners/local/LocalAttributeListener.ts
  packages/consumption/src/modules/index.ts
  packages/consumption/src/modules/requests/index.ts
  packages/consumption/src/modules/requests/itemProcessors/registerAttributeListener/RegisterAttributeListenerRequestItemProcessor.ts
  packages/consumption/test/modules/attributeListeners/AttributeListenersController.test.ts
  packages/consumption/test/modules/requests/itemProcessors/registerAttributeListener/RegisterAttributeListenerRequestItemProcessor.test.ts
  packages/content/src/requests/RequestItem.ts
  packages/content/src/requests/items/index.ts
  packages/content/src/requests/items/registerAttributeListener/RegisterAttributeListenerAcceptResponseItem.ts
  packages/content/src/requests/items/registerAttributeListener/RegisterAttributeListenerRequestItem.ts
  packages/content/src/requests/response/AcceptResponseItem.ts
  packages/runtime-types/src/consumption/LocalAttributeListenerDTO.ts
  packages/runtime-types/src/consumption/index.ts
  packages/runtime/src/Runtime.ts
  packages/runtime/src/dataViews/DataViewExpander.ts
  packages/runtime/src/dataViews/consumption/LocalAttributeListenerDVO.ts
  packages/runtime/src/dataViews/consumption/index.ts
  packages/runtime/src/dataViews/content/RequestItemDVOs.ts
  packages/runtime/src/dataViews/content/ResponseItemDVOs.ts
  packages/runtime/src/events/EventProxy.ts
  packages/runtime/src/events/consumption/AttributeListenerCreatedEvent.ts
  packages/runtime/src/events/consumption/AttributeListenerTriggeredEvent.ts
  packages/runtime/src/events/consumption/index.ts
  packages/runtime/src/extensibility/ConsumptionServices.ts
  packages/runtime/src/extensibility/facades/consumption/AttributeListenersFacade.ts
  packages/runtime/src/extensibility/facades/consumption/index.ts
  packages/runtime/src/modules/AttributeListenerModule.ts
  packages/runtime/src/modules/DeciderModule.ts
  packages/runtime/src/modules/decide/RequestConfig.ts
  packages/runtime/src/modules/index.ts
  packages/runtime/src/useCases/common/Schemas.ts
  packages/runtime/src/useCases/common/validation/ValidatableStrings.ts
  packages/runtime/src/useCases/consumption/attributeListeners/AttributeListenerMapper.ts
  packages/runtime/src/useCases/consumption/attributeListeners/GetAttributeListener.ts
  packages/runtime/src/useCases/consumption/attributeListeners/GetAttributeListeners.ts
  packages/runtime/src/useCases/consumption/attributeListeners/index.ts
  packages/runtime/src/useCases/consumption/index.ts
  packages/runtime/test/lib/RuntimeServiceProvider.ts
  packages/runtime/test/modules/AttributeListenerModule.test.ts
  packages/runtime/test/modules/DeciderModule.test.ts
  packages/runtime/test/modules/DeciderModule.unit.test.ts
Labels: breaking-change

#646 The error for missing identity on startup is not machine readable
  packages/transport/src/core/TransportCoreErrors.ts
  packages/transport/src/modules/accounts/AccountController.ts
Labels: bug

#652 Satisfy linter
  packages/app-runtime/test/lib/TestUtil.ts
  packages/consumption/test/core/TestUtil.ts
  packages/content/src/messages/Mail.ts
  packages/core-types/src/CoreDate.ts
  packages/runtime/src/DatabaseSchemaUpgrader.ts
  packages/runtime/src/useCases/transport/messages/GetMessages.ts
  packages/runtime/test/lib/QueryParamConditions.ts
  packages/transport/src/core/backbone/RESTClient.ts
  packages/transport/src/modules/files/FileController.ts
  packages/transport/src/modules/messages/MessageController.ts
  packages/transport/src/modules/messages/transmission/MessageContentWrapper.ts
  packages/transport/src/modules/relationships/RelationshipsController.ts
  packages/transport/src/modules/sync/SyncController.ts
  packages/transport/test/modules/messages/MessageContent.test.ts
  packages/transport/test/testHelpers/TestUtil.ts
Labels: chore

#653 Multiple objects with same `id` can be created in the database
  packages/consumption/test/modules/attributes/AttributesController.test.ts
  packages/runtime/test/misc/DatabaseSchemaUpgrader.test.ts
  packages/runtime/test/transport/messages.test.ts
  packages/runtime/test/transport/relationships.test.ts
  packages/transport/src/modules/accounts/AccountController.ts
Labels: bug

#659 Remove automatic child attribute creation
  packages/consumption/src/consumption/ConsumptionCoreErrors.ts
  packages/consumption/src/modules/attributes/AttributesController.ts
  packages/consumption/src/modules/attributes/local/AttributeSuccessorParams.ts
  packages/consumption/src/modules/attributes/local/CreateRepositoryAttributeParams.ts
  packages/consumption/src/modules/attributes/local/LocalAttribute.ts
  packages/consumption/test/modules/attributes/AttributesController.test.ts
  packages/runtime-types/src/consumption/LocalAttributeDTO.ts
  packages/runtime/src/DatabaseSchemaUpgrader.ts
  packages/runtime/src/useCases/common/RuntimeErrors.ts
  packages/runtime/src/useCases/common/Schemas.ts
  packages/runtime/src/useCases/consumption/attributes/AttributeMapper.ts
  packages/runtime/src/useCases/consumption/attributes/DeleteRepositoryAttribute.ts
  packages/runtime/src/useCases/consumption/attributes/GetAttributes.ts
  packages/runtime/src/useCases/consumption/attributes/NotifyPeerAboutRepositoryAttributeSuccession.ts
  packages/runtime/test/consumption/attributes.test.ts
Labels: breaking-change

#665 Remove Message caches
  packages/consumption/src/modules/notifications/NotificationsController.ts
  packages/consumption/src/modules/requests/incoming/IncomingRequestsController.ts
  packages/consumption/src/modules/requests/outgoing/OutgoingRequestsController.ts
  packages/consumption/test/modules/notifications/NotificationEnd2End.test.ts
  packages/consumption/test/modules/requests/DeleteRequest.test.ts
  packages/consumption/test/modules/requests/IncomingRequestsController.test.ts
  packages/consumption/test/modules/requests/RequestEnd2End.test.ts
  packages/consumption/test/modules/requests/testHelpers/TestObjectFactory.ts
  packages/runtime/src/useCases/consumption/notifications/ReceivedNotification.ts
  packages/runtime/src/useCases/consumption/notifications/SentNotification.ts
  packages/runtime/src/useCases/transport/messages/DownloadAttachment.ts
  packages/runtime/src/useCases/transport/messages/GetAttachmentMetadata.ts
  packages/runtime/src/useCases/transport/messages/GetMessage.ts
  packages/runtime/src/useCases/transport/messages/GetMessages.ts
  packages/runtime/src/useCases/transport/messages/MessageMapper.ts
  packages/transport/src/core/CoreSynchronizable.ts
  packages/transport/src/modules/index.ts
  packages/transport/src/modules/messages/MessageController.ts
  packages/transport/src/modules/messages/local/CachedMessage.ts
  packages/transport/src/modules/messages/local/Message.ts
  packages/transport/src/modules/messages/local/MessageRecipient.ts
  packages/transport/src/modules/sync/DatawalletModificationMapper.ts
  packages/transport/src/modules/sync/DatawalletModificationsProcessor.ts
  packages/transport/src/modules/sync/SynchronizedCollection.ts
  packages/transport/src/modules/sync/externalEventProcessors/MessageDeliveredExternalEventProcessor.ts
  packages/transport/src/modules/sync/local/DatawalletModification.ts
  packages/transport/src/modules/sync/migrations/DeviceMigrations.ts
  packages/transport/test/modules/PublicAPI.test.ts
  packages/transport/test/modules/messages/Attachment.test.ts
  packages/transport/test/modules/messages/MessageContent.test.ts
  packages/transport/test/modules/messages/MessageController.test.ts
  packages/transport/test/modules/relationships/decomposition.test.ts
  packages/transport/test/modules/sync/SyncController.messages.test.ts
Labels: breaking-change

#670 Remove Relationship caches
  packages/consumption/src/modules/attributes/AttributesController.ts
  packages/consumption/src/modules/requests/outgoing/OutgoingRequestsController.ts
  packages/consumption/test/modules/requests/RequestEnd2End.test.ts
  packages/consumption/test/modules/requests/testHelpers/TestObjectFactory.ts
  packages/runtime/src/useCases/transport/relationships/AcceptRelationship.ts
  packages/runtime/src/useCases/transport/relationships/AcceptRelationshipReactivation.ts
  packages/runtime/src/useCases/transport/relationships/DecomposeRelationship.ts
  packages/runtime/src/useCases/transport/relationships/GetRelationships.ts
  packages/runtime/src/useCases/transport/relationships/RejectRelationship.ts
  packages/runtime/src/useCases/transport/relationships/RejectRelationshipReactivation.ts
  packages/runtime/src/useCases/transport/relationships/RelationshipMapper.ts
  packages/runtime/src/useCases/transport/relationships/RequestRelationshipReactivation.ts
  packages/runtime/src/useCases/transport/relationships/RevokeRelationship.ts
  packages/runtime/src/useCases/transport/relationships/RevokeRelationshipReactivation.ts
  packages/runtime/src/useCases/transport/relationships/TerminateRelationship.ts
  packages/transport/src/modules/index.ts
  packages/transport/src/modules/relationshipTemplates/RelationshipTemplateController.ts
  packages/transport/src/modules/relationships/RelationshipsController.ts
  packages/transport/src/modules/relationships/local/CachedRelationship.ts
  packages/transport/src/modules/relationships/local/Relationship.ts
  packages/transport/src/modules/sync/DatawalletModificationsProcessor.ts
  packages/transport/src/modules/sync/SyncController.ts
  packages/transport/src/modules/sync/externalEventProcessors/RelationshipExternalEventProcessor.ts
  packages/transport/test/end2end/End2End.test.ts
  packages/transport/test/modules/PublicAPI.test.ts
  packages/transport/test/modules/relationshipTemplates/RelationshipTemplateController.test.ts
  packages/transport/test/modules/relationships/RelationshipsController.test.ts
  packages/transport/test/modules/relationships/RelationshipsCustomContent.test.ts
  packages/transport/test/modules/relationships/decomposition.test.ts
  packages/transport/test/modules/sync/SyncController.messages.test.ts
  packages/transport/test/modules/sync/SyncController.relationships.test.ts
Labels: breaking-change

#673 Remove RelationshipTemplate caches
  packages/consumption/src/modules/requests/incoming/IncomingRequestsController.ts
  packages/consumption/src/modules/requests/outgoing/OutgoingRequestsController.ts
  packages/consumption/test/modules/requests/IncomingRequestsController.test.ts
  packages/consumption/test/modules/requests/RequestEnd2End.test.ts
  packages/consumption/test/modules/requests/testHelpers/TestObjectFactory.ts
  packages/runtime/src/useCases/transport/relationshipTemplates/CreateTokenForOwnRelationshipTemplate.ts
  packages/runtime/src/useCases/transport/relationshipTemplates/GetRelationshipTemplates.ts
  packages/runtime/src/useCases/transport/relationshipTemplates/RelationshipTemplateMapper.ts
  packages/runtime/src/useCases/transport/relationships/CanCreateRelationship.ts
  packages/runtime/src/useCases/transport/relationships/utility/validateCreationContentOfRelationship.ts
  packages/runtime/test/modules/RequestModule.test.ts
  packages/transport/src/modules/index.ts
  packages/transport/src/modules/relationshipTemplates/RelationshipTemplateController.ts
  packages/transport/src/modules/relationshipTemplates/local/CachedRelationshipTemplate.ts
  packages/transport/src/modules/relationshipTemplates/local/RelationshipTemplate.ts
  packages/transport/src/modules/relationshipTemplates/local/SendRelationshipTemplateParameters.ts
  packages/transport/src/modules/relationships/RelationshipSecretController.ts
  packages/transport/src/modules/relationships/RelationshipsController.ts
  packages/transport/src/modules/sync/DatawalletModificationsProcessor.ts
  packages/transport/src/modules/sync/SyncController.ts
  packages/transport/test/end2end/End2End.test.ts
  packages/transport/test/modules/PublicAPI.test.ts
  packages/transport/test/modules/relationshipTemplates/RelationshipTemplateController.test.ts
  packages/transport/test/modules/sync/SyncController.relationships.test.ts
  packages/transport/test/utils/Reflection.test.ts
Labels: breaking-change

#678 Remove certificates transport module
  packages/runtime-types/src/transport/DeviceDTO.ts
  packages/runtime/src/useCases/transport/devices/DeviceMapper.ts
  packages/transport/src/core/DbCollectionName.ts
  packages/transport/src/core/TransportController.ts
  packages/transport/src/modules/accounts/AccountController.ts
  packages/transport/src/modules/certificates/CertificateController.ts
  packages/transport/src/modules/certificates/CertificateIssuer.ts
  packages/transport/src/modules/certificates/CertificateValidator.ts
  packages/transport/src/modules/certificates/data/Certificate.ts
  packages/transport/src/modules/certificates/data/CertificateConstraint.ts
  packages/transport/src/modules/certificates/data/CertificateContent.ts
  packages/transport/src/modules/certificates/data/CertificateItem.ts
  packages/transport/src/modules/certificates/data/constraints/CertificateBorderConstraint.ts
  packages/transport/src/modules/certificates/data/constraints/CertificateCityConstraint.ts
  packages/transport/src/modules/certificates/data/constraints/CertificateIdentityConstraint.ts
  packages/transport/src/modules/certificates/data/constraints/CertificateTimeConstraint.ts
  packages/transport/src/modules/certificates/data/items/CertificateAuthorizationItem.ts
  packages/transport/src/modules/certificates/data/items/CertificateDelegateItem.ts
  packages/transport/src/modules/certificates/data/items/CertificatePrivateAttributeItem.ts
  packages/transport/src/modules/certificates/data/items/CertificatePrivateAttributeItemSource.ts
  packages/transport/src/modules/certificates/data/items/CertificatePublicAttributeItem.ts
  packages/transport/src/modules/certificates/data/items/CertificateRoleItem.ts
  packages/transport/src/modules/devices/DeviceController.ts
  packages/transport/src/modules/devices/local/Device.ts
  packages/transport/src/modules/index.ts
  packages/transport/test/modules/PublicAPI.test.ts
  packages/transport/test/modules/certificates/CertificateIssuer.test.ts
Labels: chore

#681 Get rid of any usage in the decider module
  packages/runtime/src/modules/DeciderModule.ts
  packages/runtime/test/lib/RuntimeServiceProvider.ts
  packages/runtime/test/modules/DeciderModule.test.ts
Labels: refactoring

#683 Decider module tests are broken
  packages/runtime/src/modules/DeciderModule.ts
  packages/runtime/test/modules/DeciderModule.test.ts
Labels: test

#682 Remove the ability to automatically decide Authentication- and ConsentRequestItems
  packages/runtime/src/modules/DeciderModule.ts
  packages/runtime/src/modules/decide/RequestConfig.ts
  packages/runtime/test/modules/DeciderModule.test.ts
  packages/runtime/test/modules/DeciderModule.unit.test.ts
Labels: breaking-change

#690 Add support for sending Backbone notifications to Relationships
  .dev/appsettings.override.json
  packages/runtime/src/Runtime.ts
  packages/runtime/src/extensibility/TransportServices.ts
  packages/runtime/src/extensibility/facades/transport/BackboneNotificationsFacade.ts
  packages/runtime/src/extensibility/facades/transport/index.ts
  packages/runtime/src/useCases/common/Schemas.ts
  packages/runtime/src/useCases/transport/backboneNotifications/SendBackboneNotification.ts
  packages/runtime/src/useCases/transport/backboneNotifications/index.ts
  packages/runtime/src/useCases/transport/index.ts
  packages/runtime/test/transport/backboneNotifications.test.ts
  packages/transport/src/core/TransportController.ts
  packages/transport/src/core/TransportCoreErrors.ts
  packages/transport/src/modules/accounts/AccountController.ts
  packages/transport/src/modules/backboneNotifications/BackboneNotificationsController.ts
  packages/transport/src/modules/backboneNotifications/backbone/BackboneNotificationsClient.ts
  packages/transport/src/modules/index.ts
  packages/transport/test/modules/backboneNotifications/BackboneNotificationsController.test.ts
Labels: enhancement
