Repository nmshd/runtime, pull requests merged in 2025-01, with the labels that each got.

#380 Upgrade backbone
  .dev/appsettings.override.json
  .dev/compose.backbone.env
Labels: chore

#381 RequestConfig is skipped if false is configured as value
  packages/runtime/src/modules/DeciderModule.ts
  packages/runtime/src/modules/decide/RequestConfig.ts
  packages/runtime/test/modules/DeciderModule.test.ts
Labels: bug

#382 Improve pipeline debug logging for SynchronizedCollection data inconsistencies
  packages/transport/src/modules/sync/SynchronizedCollection.ts
Labels: chore

#383 Add Runtime errors for IdentityMetadata use cases
  packages/runtime/src/useCases/common/RuntimeErrors.ts
  packages/runtime/src/useCases/consumption/identityMetadata/DeleteIdentityMetadata.ts
  packages/runtime/src/useCases/consumption/identityMetadata/GetIdentityMetadata.ts
  packages/runtime/src/useCases/consumption/identityMetadata/UpsertIdentityMetadata.ts
  packages/runtime/test/consumption/identityMetadata.test.ts
Labels: enhancement

#384 Retry processing password protected references for wrong passwords
  packages/app-runtime/src/AppStringProcessor.ts
  packages/app-runtime/src/extensibility/ui/IUIBridge.ts
  packages/app-runtime/test/lib/FakeUIBridge.ts
  packages/app-runtime/test/lib/MockUIBridge.matchers.ts
  packages/app-runtime/test/lib/MockUIBridge.ts
  packages/app-runtime/test/runtime/AppStringProcessor.test.ts
Labels: enhancement

#386 Remove FerretDB pipelines
  .github/workflows/test.yml
Labels: ci

#387 Extend RequestConfig of DeciderModule depending on existence of Relationship
  packages/runtime/src/modules/DeciderModule.ts
  packages/runtime/src/modules/decide/RequestConfig.ts
  packages/runtime/test/modules/DeciderModule.test.ts
Labels: enhancement

#338 Improve CreateRepositoryAttribute error messages
  packages/consumption/src/consumption/ConsumptionCoreErrors.ts
  packages/runtime/scripts/buildSchemas.mjs
  packages/runtime/src/useCases/common/Schemas.ts
  packages/runtime/src/useCases/consumption/attributes/CreateRepositoryAttribute.ts
  packages/runtime/test/consumption/attributes.test.ts
Labels: bug

#389 Do not emit DatawalletSynchronizedEvent with disabled Datawallet
  packages/runtime/src/events/transport/DatawalletSynchronizedEvent.ts
  packages/transport/src/events/DatawalletSynchronizedEvent.ts
  packages/transport/src/modules/sync/SyncController.ts
Labels: bug

#393 `schemaURL` of XML Attributes is not nullable
  packages/consumption/test/modules/attributes/AttributesController.test.ts
  packages/content/src/attributes/types/identity/SchematizedXML.ts
  packages/content/src/attributes/types/proprietary/ProprietaryXML.ts
Labels: bug

#394 Move check for RepositoryAttribute duplicates to AttributesController
  packages/consumption/src/modules/attributes/AttributesController.ts
  packages/consumption/src/modules/common/flattenObject.ts
  packages/consumption/src/modules/common/index.ts
  packages/runtime/src/useCases/consumption/attributes/CreateRepositoryAttribute.ts
Labels: refactoring

#396 Add CanCreateRepositoryAttribute use case
  packages/runtime/scripts/buildSchemas.mjs
  packages/runtime/src/extensibility/facades/consumption/AttributesFacade.ts
  packages/runtime/src/useCases/common/Schemas.ts
  packages/runtime/src/useCases/consumption/attributes/CanCreateRepositoryAttribute.ts
  packages/runtime/src/useCases/consumption/attributes/CreateRepositoryAttribute.ts
  packages/runtime/src/useCases/consumption/attributes/IdentityAttributeValueValidator.ts
  packages/runtime/src/useCases/consumption/attributes/index.ts
  packages/runtime/test/consumption/attributes.test.ts
Labels: enhancement

#400 Audit fix
  package-lock.json
  package.json
  packages/app-runtime/package.json
  packages/consumption/package.json
  packages/runtime/package.json
  packages/transport/package.json
Labels: dependencies

#403 FerretDB v2 local testing setup
  .dev/compose.yml
  packages/consumption/package.json
  packages/runtime/package.json
  packages/transport/package.json
Labels: chore

#404 Bump backbone
  .dev/appsettings.override.json
  .dev/compose.backbone.env
Labels: dependencies

#395 AppRuntime SSE Module
  .dev/appsettings.override.json
  .dev/compose.backbone.yml
  .github/workflows/test.yml
  package-lock.json
  packages/app-runtime/package.json
  packages/app-runtime/src/AppConfig.ts
  packages/app-runtime/src/AppRuntime.ts
  packages/app-runtime/src/AppStringProcessor.ts
  packages/app-runtime/src/modules/AppSyncModule.ts
  packages/app-runtime/src/modules/PushNotificationModule.ts
  packages/app-runtime/src/modules/SSEModule.ts
  packages/app-runtime/src/modules/appSync/index.ts
  packages/app-runtime/src/modules/index.ts
  packages/app-runtime/src/modules/pushNotifications/IBackboneEventContent.ts
  packages/app-runtime/src/modules/pushNotifications/index.ts
  packages/app-runtime/src/multiAccount/MultiAccountController.ts
  packages/app-runtime/test/lib/FakeUIBridge.ts
  packages/app-runtime/test/lib/MockEventBus.ts
  packages/app-runtime/test/lib/TestUtil.ts
  packages/app-runtime/test/lib/natives/FakeNativeBootstrapper.ts
  packages/app-runtime/test/modules/PushNotification.test.ts
  packages/app-runtime/test/modules/SSEModule.test.ts
  packages/app-runtime/test/runtime/TranslationProvider.test.ts
  packages/transport/src/core/backbone/ClientResult.ts
  packages/transport/src/core/backbone/PlatformParameters.ts
  packages/transport/src/core/backbone/RESTClient.ts
  packages/transport/src/modules/messages/MessageController.ts
Labels: enhancement

#407 Make app-runtime modules configurable and simplfy the app-runtime startup
  packages/app-runtime/src/AppConfig.ts
  packages/app-runtime/src/AppRuntime.ts
  packages/app-runtime/src/natives/INativeConfigAccess.ts
  packages/app-runtime/test/lib/TestUtil.ts
  packages/app-runtime/test/lib/natives/FakeNativeConfigAccess.ts
Labels: bug

#408 Don't use serval's `unionTypes` with primitive types
  packages/content/src/attributes/hints/ValueHints.ts
Labels: bug

#405 Rename TestIdentities
  packages/consumption/test/modules/requests/itemProcessors/createAttribute/Context.ts
  packages/consumption/test/modules/requests/itemProcessors/createAttribute/CreateAttributeRequestItemProcessor.test.ts
  packages/consumption/test/modules/requests/itemProcessors/createAttribute/TestIdentity.ts
Labels: test

#409 Simplify app-runtime natives
  packages/app-runtime/src/AppConfig.ts
  packages/app-runtime/src/modules/AppRuntimeModule.ts
  packages/app-runtime/src/modules/PushNotificationModule.ts
  packages/app-runtime/src/modules/appEvents/AppLaunchModule.ts
  packages/app-runtime/src/natives/INativeDeviceInfoAccess.ts
  packages/app-runtime/src/natives/INativeEnvironment.ts
  packages/app-runtime/src/natives/index.ts
  packages/app-runtime/test/lib/TestUtil.ts
  packages/app-runtime/test/lib/natives/FakeNativeBootstrapper.ts
  packages/app-runtime/test/lib/natives/FakeNativeDeviceInfoAccess.ts
  packages/app-runtime/test/modules/PushNotification.test.ts
Labels: enhancement

#411 Upgrade RabbitMQ for local backbone
  .dev/compose.backbone.yml
Labels: dependencies
