Repository nmshd/runtime, pull requests merged in 2025-02, with the labels that each got.

#401 Relationship creation without accepting Request of RelationshipTemplateContent
  packages/runtime/src/useCases/common/RuntimeErrors.ts
  packages/runtime/src/useCases/transport/relationships/CanCreateRelationship.ts
  packages/runtime/src/useCases/transport/relationships/CreateRelationship.ts
  packages/runtime/src/useCases/transport/relationships/utility/validateCreationContentOfRelationship.ts
  packages/runtime/test/dataViews/RelationshipDVO.test.ts
  packages/runtime/test/lib/testUtils.ts
  packages/runtime/test/transport/relationships.test.ts
Labels: bug

#410 Prevent creation of RepositoryAttribute duplicates by accepting a CreateAttributeRequestItem
  packages/consumption/src/modules/attributes/AttributesController.ts
  packages/consumption/src/modules/requests/itemProcessors/createAttribute/CreateAttributeRequestItemProcessor.ts
  packages/consumption/test/modules/requests/itemProcessors/createAttribute/Context.ts
  packages/consumption/test/modules/requests/itemProcessors/createAttribute/CreateAttributeRequestItemProcessor.test.ts
  packages/runtime/test/dataViews/requestItems/CreateIdentityAttributeRequestItemDVO.test.ts
Labels: enhancement

#414 Wrong i18n usage
  packages/runtime/src/dataViews/DataViewExpander.ts
Labels: bug

#415 Remove unused code
  packages/app-runtime/src/AppConfig.ts
  packages/app-runtime/src/AppRuntime.ts
  packages/app-runtime/src/modules/appEvents/AppLaunchModule.ts
  packages/app-runtime/src/modules/appEvents/index.ts
  packages/app-runtime/src/natives/events/UrlOpenEvent.ts
  packages/app-runtime/src/natives/events/index.ts
Labels: chore

#416 Add `isBackupDevice` to DeviceSharedSecret
  packages/app-runtime/test/lib/MockUIBridge.matchers.ts
  packages/app-runtime/test/runtime/AppStringProcessor.test.ts
  packages/runtime/src/types/transport/DeviceOnboardingInfoDTO.ts
  packages/runtime/src/useCases/transport/devices/DeviceMapper.ts
  packages/transport/src/modules/devices/DeviceSecretController.ts
  packages/transport/src/modules/devices/transmission/DeviceSharedSecret.ts
Labels: enhancement

#412 Improve `test.each` test name individualisation
  packages/consumption/test/modules/requests/DecideRequestParametersValidator.test.ts
  packages/consumption/test/modules/requests/itemProcessors/createAttribute/CreateAttributeRequestItemProcessor.test.ts
  packages/consumption/test/modules/requests/itemProcessors/shareAttribute/ShareAttributeRequestItemProcessor.test.ts
  packages/content/test/attributeValues/ProprietaryJSON.test.ts
  packages/content/test/attributes/RelationshipAttributeHints.test.ts
  packages/content/test/attributes/ThirdPartyRelationshipAttributeQuery.test.ts
Labels: refactoring, test

#398 Deleting a SharedAttribute does not validate if it's possible to send the Notification
  packages/runtime/src/useCases/common/RuntimeErrors.ts
  packages/runtime/src/useCases/consumption/attributes/DeleteOwnSharedAttributeAndNotifyPeer.ts
  packages/runtime/src/useCases/consumption/attributes/DeletePeerSharedAttributeAndNotifyOwner.ts
  packages/runtime/src/useCases/consumption/attributes/DeleteThirdPartyRelationshipAttributeAndNotifyPeer.ts
  packages/runtime/test/consumption/attributes.test.ts
  packages/runtime/test/lib/testUtils.ts
  packages/runtime/test/transport/messages.test.ts
  packages/transport/src/modules/messages/MessageController.ts
Labels: bug

#417 Rename handleRelationshipTemplateProcessed method
  packages/app-runtime/src/modules/appEvents/RelationshipTemplateProcessedModule.ts
Labels: refactoring

#419 Enrich metadata of File with tags
  packages/runtime/src/dataViews/transport/FileDVO.ts
  packages/runtime/src/types/transport/FileDTO.ts
  packages/runtime/src/useCases/common/Schemas.ts
  packages/runtime/src/useCases/transport/files/FileMapper.ts
  packages/runtime/src/useCases/transport/files/GetFiles.ts
  packages/runtime/src/useCases/transport/files/UploadOwnFile.ts
  packages/runtime/test/transport/files.test.ts
  packages/transport/src/modules/files/FileController.ts
  packages/transport/src/modules/files/local/CachedFile.ts
  packages/transport/src/modules/files/local/SendFileParameters.ts
  packages/transport/src/modules/files/transmission/FileMetadata.ts
  packages/transport/test/modules/files/FileController.test.ts
  packages/transport/test/testHelpers/TestUtil.ts
Labels: enhancement

#421 Return all CanDecide errors simultaneously
  packages/consumption/src/modules/common/index.ts
  packages/consumption/src/modules/common/mergeResults.ts
  packages/consumption/src/modules/requests/incoming/DecideRequestParametersValidator.ts
  packages/consumption/src/modules/requests/incoming/IncomingRequestsController.ts
  packages/consumption/test/modules/requests/DecideRequestParametersValidator.test.ts
  packages/consumption/test/modules/requests/IncomingRequestsController.test.ts
Labels: enhancement

#424 Extent testUtil to delete all shared Attributes
  packages/runtime/test/consumption/attributes.test.ts
  packages/runtime/test/dataViews/SharedToPeerAttributeDVO.test.ts
  packages/runtime/test/dataViews/requestItems/ComplexReadAttributeRequestItemDVO.test.ts
  packages/runtime/test/dataViews/requestItems/CreateIdentityAttributeRequestItemDVO.test.ts
  packages/runtime/test/dataViews/requestItems/DeleteAttributeRequestItemDVO.test.ts
  packages/runtime/test/dataViews/requestItems/ReadAttributeRequestItemDVO.test.ts
  packages/runtime/test/lib/testUtils.ts
  packages/runtime/test/transport/relationships.test.ts
Labels: test

#425 The recovery kit token is not deleted from the backbone after successful onboarding
  packages/app-runtime/src/multiAccount/MultiAccountController.ts
  packages/app-runtime/test/runtime/Onboarding.test.ts
Labels: bug

#423 Prevent creation of RepositoryAttribute duplicates by accepting a ReadAttributeRequestItem
  packages/consumption/src/modules/requests/itemProcessors/readAttribute/AcceptReadAttributeRequestItemParameters.ts
  packages/consumption/src/modules/requests/itemProcessors/readAttribute/ReadAttributeRequestItemProcessor.ts
  packages/consumption/test/core/TestUtil.ts
  packages/consumption/test/modules/requests/itemProcessors/readAttribute/ReadAttributeRequestItemProcessor.test.ts
Labels: enhancement

#427 The RequestModule creates expired requests in the `PeerRelationshipTemplateLoaded` event handler
  packages/app-runtime/src/modules/appEvents/RelationshipTemplateProcessedModule.ts
  packages/app-runtime/test/lib/MockUIBridge.matchers.ts
  packages/app-runtime/test/lib/TestUtil.ts
  packages/app-runtime/test/modules/appEvents/RelationshipTemplateProcessedModule.test.ts
  packages/runtime/src/events/consumption/RelationshipTemplateProcessedEvent.ts
  packages/runtime/src/modules/RequestModule.ts
Labels: bug

#429 Add more tests for RelationshipTemplateProcessedResult.RequestExpired
  .dev/compose.backbone.yml
  packages/app-runtime/test/modules/appEvents/RelationshipTemplateProcessedModule.test.ts
  packages/runtime/test/modules/RequestModule.test.ts
Labels: test

#433 Delete incoming requests
  packages/consumption/src/consumption/ConsumptionCoreErrors.ts
  packages/consumption/src/modules/requests/incoming/IncomingRequestsController.ts
  packages/consumption/test/modules/requests/DeleteRequest.test.ts
  packages/runtime/src/extensibility/facades/consumption/IncomingRequestsFacade.ts
  packages/runtime/src/useCases/common/Schemas.ts
  packages/runtime/src/useCases/consumption/requests/DeleteIncomingRequest.ts
  packages/runtime/src/useCases/consumption/requests/index.ts
  packages/runtime/test/consumption/requests.test.ts
Labels: enhancement

#434 Fix typo and clean up ReadAttributeRequestItemProcessor test
  packages/consumption/src/modules/requests/itemProcessors/createAttribute/CreateAttributeRequestItemProcessor.ts
  packages/consumption/test/modules/requests/itemProcessors/readAttribute/ReadAttributeRequestItemProcessor.test.ts
Labels: refactoring

#438 Refactor ReadAttributeRequestItemProcessor
  packages/consumption/src/modules/requests/itemProcessors/readAttribute/ReadAttributeRequestItemProcessor.ts
Labels: refactoring

#440 Make CreateAttributeRequestItemProcessor tests independent
  packages/consumption/test/modules/requests/itemProcessors/createAttribute/CreateAttributeRequestItemProcessor.test.ts
Labels: test

#439 Notifying about RepositoryAttribute succession isn't possible if additional own shared IdentityAttribute with deletionInfo exsists
  packages/consumption/src/modules/attributes/AttributesController.ts
  packages/runtime/src/useCases/common/RuntimeErrors.ts
  packages/runtime/src/useCases/consumption/attributes/NotifyPeerAboutRepositoryAttributeSuccession.ts
  packages/runtime/test/consumption/attributes.test.ts
Labels: bug
