Repository nmshd/runtime, pull requests merged in 2025-03, with the labels that each got.

#432 Add UseCases to delete Files, RelationshipTemplates and Tokens
  packages/runtime/src/extensibility/facades/transport/FilesFacade.ts
  packages/runtime/src/extensibility/facades/transport/RelationshipTemplatesFacade.ts
  packages/runtime/src/extensibility/facades/transport/TokensFacade.ts
  packages/runtime/src/useCases/common/Schemas.ts
  packages/runtime/src/useCases/transport/files/DeleteFile.ts
  packages/runtime/src/useCases/transport/files/index.ts
  packages/runtime/src/useCases/transport/relationshipTemplates/DeleteRelationshipTemplate.ts
  packages/runtime/src/useCases/transport/relationshipTemplates/index.ts
  packages/runtime/src/useCases/transport/tokens/DeleteToken.ts
  packages/runtime/src/useCases/transport/tokens/index.ts
  packages/runtime/test/transport/files.test.ts
  packages/runtime/test/transport/relationshipTemplates.test.ts
  packages/runtime/test/transport/tokens.test.ts
  packages/transport/src/modules/files/FileController.ts
  packages/transport/src/modules/relationshipTemplates/RelationshipTemplateController.ts
  packages/transport/src/modules/tokens/TokenController.ts
  packages/transport/test/modules/files/FileController.test.ts
  packages/transport/test/modules/relationshipTemplates/RelationshipTemplateController.test.ts
  packages/transport/test/modules/tokens/TokenController.test.ts
Labels: enhancement

#399 Make `title` optional in FileDTO
  packages/runtime/src/dataViews/DataViewExpander.ts
  packages/runtime/src/types/transport/FileDTO.ts
  packages/runtime/src/useCases/transport/files/FileMapper.ts
Labels: breaking-change, refactoring

#301 Remove template from relationship
  packages/consumption/test/modules/requests/testHelpers/TestObjectFactory.ts
  packages/runtime/src/dataViews/DataViewExpander.ts
  packages/runtime/src/modules/RequestModule.ts
  packages/runtime/src/types/transport/RelationshipDTO.ts
  packages/runtime/src/useCases/common/Schemas.ts
  packages/runtime/src/useCases/transport/relationships/GetRelationships.ts
  packages/runtime/src/useCases/transport/relationships/RelationshipMapper.ts
  packages/runtime/test/consumption/requests.test.ts
  packages/runtime/test/dataViews/RelationshipDVO.test.ts
  packages/runtime/test/lib/testUtils.ts
  packages/runtime/test/transport/relationships.test.ts
  packages/transport/src/modules/relationshipTemplates/RelationshipTemplateController.ts
  packages/transport/src/modules/relationships/RelationshipsController.ts
  packages/transport/src/modules/relationships/local/CachedRelationship.ts
  packages/transport/src/modules/relationships/local/Relationship.ts
  packages/transport/test/end2end/End2End.test.ts
  packages/transport/test/modules/relationshipTemplates/RelationshipTemplateController.test.ts
  packages/transport/test/modules/relationships/RelationshipsController.test.ts
  packages/transport/test/modules/relationships/decomposition.test.ts
  packages/transport/test/modules/sync/SyncController.relationships.test.ts
Labels: breaking-change, refactoring

#442 Make `title` of AuthenticationRequestItem mandatory
  packages/app-runtime/test/modules/appEvents/RelationshipTemplateProcessedModule.test.ts
  packages/content/src/requests/items/authentication/AuthenticationRequestItem.ts
  packages/runtime/src/dataViews/consumption/DecidableRequestItemDVOs.ts
  packages/runtime/src/dataViews/content/RequestItemDVOs.ts
  packages/runtime/src/useCases/common/Schemas.ts
  packages/runtime/test/modules/DeciderModule.test.ts
  packages/runtime/test/transport/messages.test.ts
Labels: breaking-change, enhancement

#446 `unsubscribeFromAllEvents` is not safe to be called in every module
  packages/app-runtime/src/modules/AppSyncModule.ts
  packages/app-runtime/src/modules/PushNotificationModule.ts
  packages/app-runtime/src/modules/SSEModule.ts
  packages/app-runtime/src/modules/appEvents/MailReceivedModule.ts
  packages/app-runtime/src/modules/appEvents/OnboardingChangeReceivedModule.ts
  packages/app-runtime/src/modules/appEvents/RelationshipTemplateProcessedModule.ts
  packages/app-runtime/src/modules/runtimeEvents/IdentityDeletionProcessStatusChangedModule.ts
  packages/app-runtime/src/modules/runtimeEvents/MessageReceivedModule.ts
  packages/app-runtime/src/modules/runtimeEvents/RelationshipChangedModule.ts
  packages/app-runtime/test/runtime/RuntimeModuleLoadingTest.test.ts
  packages/runtime/src/extensibility/modules/RuntimeModule.ts
  packages/runtime/src/modules/AttributeListenerModule.ts
  packages/runtime/src/modules/DeciderModule.ts
  packages/runtime/src/modules/MessageModule.ts
  packages/runtime/src/modules/NotificationModule.ts
  packages/runtime/src/modules/RequestModule.ts
Labels: bug

#441 Accepting a CreateAttributeRequestItem sends an AttributeAlreadySharedAcceptResponseItem if already shared Attribute was deleted by peer
  packages/consumption/src/modules/attributes/AttributesController.ts
  packages/consumption/src/modules/requests/itemProcessors/createAttribute/CreateAttributeRequestItemProcessor.ts
  packages/consumption/src/modules/requests/itemProcessors/proposeAttribute/ProposeAttributeRequestItemProcessor.ts
  packages/consumption/src/modules/requests/itemProcessors/readAttribute/ReadAttributeRequestItemProcessor.ts
  packages/consumption/test/modules/attributes/AttributesController.test.ts
  packages/consumption/test/modules/requests/itemProcessors/createAttribute/Context.ts
  packages/consumption/test/modules/requests/itemProcessors/createAttribute/CreateAttributeRequestItemProcessor.test.ts
Labels: bug

#420 Remove `validFrom` and `validTo` from AbstractAttribute
  packages/consumption/src/modules/attributes/AttributesController.ts
  packages/consumption/src/modules/attributes/local/QueryTranslator.ts
  packages/consumption/src/modules/requests/itemProcessors/utility/validateAttributeMatchesWithQuery.ts
  packages/consumption/test/modules/attributes/AttributesController.test.ts
  packages/consumption/test/modules/requests/itemProcessors/readAttribute/ReadAttributeRequestItemProcessor.test.ts
  packages/consumption/test/modules/requests/itemProcessors/utility/validateAttributeMatchesWithQuery.test.ts
  packages/content/src/attributes/AbstractAttribute.ts
  packages/content/src/attributes/IdentityAttributeQuery.ts
  packages/content/src/attributes/RelationshipAttributeQuery.ts
  packages/content/src/attributes/ThirdPartyRelationshipAttributeQuery.ts
  packages/content/test/attributes/IdentityAttribute.test.ts
  packages/runtime/src/dataViews/DataViewExpander.ts
  packages/runtime/src/dataViews/content/AttributeDVOs.ts
  packages/runtime/src/modules/DeciderModule.ts
  packages/runtime/src/modules/decide/RequestConfig.ts
  packages/runtime/src/useCases/common/Schemas.ts
  packages/runtime/src/useCases/consumption/attributes/CanCreateRepositoryAttribute.ts
  packages/runtime/src/useCases/consumption/attributes/CreateAndShareRelationshipAttribute.ts
  packages/runtime/src/useCases/consumption/attributes/CreateRepositoryAttribute.ts
  packages/runtime/src/useCases/consumption/attributes/GetAttributes.ts
  packages/runtime/src/useCases/consumption/attributes/GetOwnSharedAttributes.ts
  packages/runtime/src/useCases/consumption/attributes/GetPeerSharedAttributes.ts
  packages/runtime/src/useCases/consumption/attributes/GetRepositoryAttributes.ts
  packages/runtime/src/useCases/consumption/attributes/SucceedRelationshipAttributeAndNotifyPeer.ts
  packages/runtime/src/useCases/consumption/attributes/SucceedRepositoryAttribute.ts
  packages/runtime/test/consumption/attributes.test.ts
  packages/runtime/test/dataViews/IQLQueryExpanded.test.ts
  packages/runtime/test/dataViews/IdentityAttributeQueryExpanded.test.ts
  packages/runtime/test/modules/DeciderModule.test.ts
Labels: breaking-change, refactoring

#436 Add validation for `tags` of Attributes
  package-lock.json
  packages/consumption/package.json
  packages/consumption/src/consumption/ConsumptionCoreErrors.ts
  packages/consumption/src/modules/attributes/AttributesController.ts
  packages/consumption/src/modules/requests/itemProcessors/createAttribute/CreateAttributeRequestItemProcessor.ts
  packages/consumption/src/modules/requests/itemProcessors/proposeAttribute/ProposeAttributeRequestItemProcessor.ts
  packages/consumption/src/modules/requests/itemProcessors/readAttribute/ReadAttributeRequestItemProcessor.ts
  packages/consumption/src/modules/requests/itemProcessors/shareAttribute/ShareAttributeRequestItemProcessor.ts
  packages/consumption/test/modules/attributes/AttributesController.test.ts
  packages/consumption/test/modules/requests/itemProcessors/createAttribute/Context.ts
  packages/consumption/test/modules/requests/itemProcessors/createAttribute/CreateAttributeRequestItemProcessor.test.ts
  packages/consumption/test/modules/requests/itemProcessors/proposeAttribute/ProposeAttributeRequestItemProcessor.test.ts
  packages/consumption/test/modules/requests/itemProcessors/readAttribute/ReadAttributeRequestItemProcessor.test.ts
  packages/consumption/test/modules/requests/itemProcessors/shareAttribute/ShareAttributeRequestItemProcessor.test.ts
  packages/consumption/test/modules/requests/itemProcessors/utility/validateAttributeMatchesWithQuery.test.ts
  packages/content/test/attributes/IQLQuery.test.ts
  packages/content/test/attributes/IdentityAttributeQuery.test.ts
  packages/runtime/test/consumption/attributes.test.ts
  packages/runtime/test/consumption/iqlQuery.test.ts
  packages/runtime/test/dataViews/IQLQueryExpanded.test.ts
  packages/runtime/test/dataViews/IdentityAttributeQueryExpanded.test.ts
  packages/runtime/test/dataViews/requestItems/ProposeAttributeRequestItemDVO.test.ts
  packages/runtime/test/dataViews/requestItems/ReadAttributeRequestItemDVO.test.ts
  packages/runtime/test/modules/DeciderModule.test.ts
Labels: breaking-change, enhancement

#437 Trim whitespaces when creating a RepositoryAttribute
  packages/consumption/src/modules/attributes/AttributesController.ts
  packages/consumption/test/modules/attributes/AttributesController.test.ts
  packages/consumption/test/modules/requests/itemProcessors/createAttribute/Context.ts
  packages/consumption/test/modules/requests/itemProcessors/createAttribute/CreateAttributeRequestItemProcessor.test.ts
  packages/consumption/test/modules/requests/itemProcessors/proposeAttribute/ProposeAttributeRequestItemProcessor.test.ts
  packages/consumption/test/modules/requests/itemProcessors/readAttribute/ReadAttributeRequestItemProcessor.test.ts
  packages/runtime/test/consumption/attributes.test.ts
Labels: enhancement

#450 Failing tests after merged pull requests
  packages/consumption/test/modules/attributes/AttributesController.test.ts
  packages/consumption/test/modules/requests/itemProcessors/createAttribute/CreateAttributeRequestItemProcessor.test.ts
  packages/runtime/test/consumption/attributes.test.ts
Labels: bug

#451 Remove `onlyValid` params
  packages/consumption/src/modules/attributes/AttributesController.ts
  packages/runtime/src/dataViews/DataViewExpander.ts
  packages/runtime/src/useCases/common/Schemas.ts
  packages/runtime/src/useCases/consumption/attributes/GetAttributes.ts
  packages/runtime/src/useCases/consumption/attributes/GetOwnSharedAttributes.ts
  packages/runtime/src/useCases/consumption/attributes/GetPeerSharedAttributes.ts
Labels: breaking-change, refactoring

#445 Use standardized test values
  packages/app-runtime/test/modules/MessageEventing.test.ts
  packages/consumption/test/modules/attributes/AttributesController.test.ts
  packages/consumption/test/modules/requests/itemProcessors/readAttribute/ReadAttributeRequestItemProcessor.test.ts
  packages/content/test/attributeValues/AddressValueTests.test.ts
  packages/content/test/attributes/EMailAddress.test.ts
  packages/content/test/messages/Mail.test.ts
  packages/runtime/test/consumption/attributes.test.ts
  packages/runtime/test/dataViews/DraftIdentityAttributeDVO.test.ts
  packages/runtime/test/dataViews/IQLQueryExpanded.test.ts
  packages/runtime/test/dataViews/MessageDVO.test.ts
  packages/runtime/test/dataViews/RepositoryAttributeDVO.test.ts
  packages/runtime/test/lib/testUtils.ts
  packages/runtime/test/transport/messages.test.ts
  packages/runtime/test/transport/relationships.test.ts
  packages/transport/test/end2end/End2End.test.ts
  packages/transport/test/modules/certificates/CertificateIssuer.test.ts
  packages/transport/test/modules/messages/MessageContent.test.ts
Labels: test

#454 Reduce dependabot npm updates reviewers
  .github/dependabot.yml
Labels: chore

#457 Move references to core types package
  .ci/publishNpm.sh
  .ci/runChecks.sh
  .github/workflows/publish.yml
  README_dev.md
  package-lock.json
  package.json
  packages/app-runtime/src/AppStringProcessor.ts
  packages/app-runtime/src/multiAccount/MultiAccountController.ts
  packages/consumption/src/consumption/ConsumptionIds.ts
  packages/consumption/test/modules/requests/DecideRequestParametersValidator.test.ts
  packages/consumption/test/modules/requests/IncomingRequestsController.test.ts
  packages/consumption/test/modules/requests/RequestsIntegrationTest.ts
  packages/consumption/test/modules/requests/itemProcessors/deleteAttribute/DeleteAttributeRequestItemProcessor.test.ts
  packages/consumption/test/modules/requests/itemProcessors/proposeAttribute/ProposeAttributeRequestItemProcessor.test.ts
  packages/consumption/test/modules/requests/itemProcessors/readAttribute/ReadAttributeRequestItemProcessor.test.ts
  packages/core-types/package.json
  packages/core-types/src/CoreIdHelper.ts
  packages/core-types/src/Random.ts
  packages/core-types/src/SharedPasswordProtection.ts
  packages/core-types/src/index.ts
  packages/core-types/src/references/FileReference.ts
  packages/core-types/src/references/Reference.ts
  packages/core-types/src/references/index.ts
  packages/core-types/test/Random.test.ts
  packages/runtime/src/useCases/transport/relationshipTemplates/CreateTokenForOwnRelationshipTemplate.ts
  packages/runtime/src/useCases/transport/relationshipTemplates/CreateTokenQRCodeForOwnRelationshipTemplate.ts
  packages/runtime/test/consumption/attributes.test.ts
  packages/runtime/test/consumption/identityMetadata.test.ts
  packages/runtime/test/consumption/notifications.test.ts
  packages/runtime/test/transport/identityDeletionProcess.test.ts
  packages/runtime/test/transport/relationships.test.ts
  packages/transport/src/core/TransportIds.ts
  packages/transport/src/core/backbone/BackboneIds.ts
  packages/transport/src/core/backbone/RESTClient.ts
  packages/transport/src/core/index.ts
  packages/transport/src/core/types/PasswordProtection.ts
  packages/transport/src/core/types/index.ts
  packages/transport/src/modules/files/FileController.ts
  packages/transport/src/modules/files/local/File.ts
  packages/transport/src/modules/index.ts
  packages/transport/src/modules/messages/MessageController.ts
  packages/transport/src/modules/messages/transmission/MessageContentWrapper.ts
  packages/transport/src/modules/relationshipTemplates/transmission/RelationshipTemplateReference.ts
  packages/transport/src/modules/tokens/transmission/TokenContentRelationshipTemplate.ts
  packages/transport/src/modules/tokens/transmission/TokenReference.ts
  packages/transport/src/util/PasswordGenerator.ts
  packages/transport/src/util/index.ts
  packages/transport/test/end2end/End2End.test.ts
  packages/transport/test/modules/files/FileReference.test.ts
  packages/transport/test/modules/sync/SynchronizedCollection.test.ts
  packages/transport/test/modules/tokens/TokenContent.test.ts
  packages/transport/test/modules/tokens/TokenController.test.ts
  packages/transport/test/testHelpers/FakeSyncClient.ts
  packages/transport/test/utils/Reflection.test.ts
Labels: refactoring

#458 Use descriptive File properties
  packages/consumption/test/core/TestUtil.ts
  packages/runtime/test/lib/testUtils.ts
  packages/transport/test/modules/sync/SyncController.files.test.ts
Labels: test

#456 Add TransferFileOwnershipRequestItem
  package-lock.json
  packages/consumption/package.json
  packages/consumption/src/consumption/ConsumptionController.ts
  packages/consumption/src/modules/requests/index.ts
  packages/consumption/src/modules/requests/itemProcessors/transferFileOwnership/TransferFileOwnershipRequestItemProcessor.ts
  packages/consumption/test/core/TestUtil.ts
  packages/consumption/test/modules/requests/itemProcessors/transferFileOwnership/TransferFileOwnershipRequestItemProcessor.test.ts
  packages/content/package.json
  packages/content/src/requests/RequestItem.ts
  packages/content/src/requests/items/index.ts
  packages/content/src/requests/items/transferFileOwnership/TransferFileOwnershipAcceptResponseItem.ts
  packages/content/src/requests/items/transferFileOwnership/TransferFileOwnershipRequestItem.ts
  packages/content/test/requests/items/TransferFileOwnershipRequestItem.test.ts
  packages/core-types/package.json
  packages/runtime/package.json
  packages/runtime/src/dataViews/DataViewExpander.ts
  packages/runtime/src/dataViews/consumption/DecidableRequestItemDVOs.ts
  packages/runtime/src/dataViews/content/RequestItemDVOs.ts
  packages/runtime/src/dataViews/content/ResponseItemDVOs.ts
  packages/runtime/src/modules/decide/RequestConfig.ts
  packages/runtime/src/useCases/common/Schemas.ts
  packages/runtime/test/dataViews/requestItems/TransferFileOwnershipRequestItemDVO.test.ts
  packages/runtime/test/modules/DeciderModule.test.ts
  packages/transport/package.json
Labels: enhancement

#449 Allow to specify RepositoryAttribute duplicate in AcceptReadAttributeRequestItemParametersWithNewAttribute
  packages/consumption/src/modules/requests/itemProcessors/createAttribute/CreateAttributeRequestItemProcessor.ts
  packages/consumption/src/modules/requests/itemProcessors/readAttribute/ReadAttributeRequestItemProcessor.ts
  packages/consumption/src/modules/requests/itemProcessors/utility/createAppropriateResponseItem.ts
  packages/consumption/test/modules/requests/itemProcessors/readAttribute/ReadAttributeRequestItemProcessor.test.ts
Labels: enhancement

#459 Refactor ProposeAttributeRequestItemProcessor tests
  packages/consumption/test/modules/requests/itemProcessors/proposeAttribute/ProposeAttributeRequestItemProcessor.test.ts
  packages/consumption/test/modules/requests/itemProcessors/readAttribute/ReadAttributeRequestItemProcessor.test.ts
Labels: test

#460 Prevent creation of RepositoryAttribute duplicates by accepting a ProposeAttributeRequestItem
  packages/consumption/src/modules/requests/itemProcessors/proposeAttribute/AcceptProposeAttributeRequestItemParameters.ts
  packages/consumption/src/modules/requests/itemProcessors/proposeAttribute/ProposeAttributeRequestItemProcessor.ts
  packages/consumption/src/modules/requests/itemProcessors/utility/createAppropriateResponseItem.ts
  packages/consumption/test/modules/requests/itemProcessors/proposeAttribute/ProposeAttributeRequestItemProcessor.test.ts
Labels: enhancement

#462 Bump Backbone to 6.34.2
  .dev/appsettings.override.json
  .dev/compose.backbone.env
  .github/workflows/test.yml
Labels: dependencies

#464 Refactor ShareAttributeRequestItemProcessor test
  packages/consumption/test/modules/requests/itemProcessors/shareAttribute/ShareAttributeRequestItemProcessor.test.ts
Labels: test

#467 Standardized capitalization of terms
  README.md
  packages/app-runtime/README.md
  packages/app-runtime/src/AppRuntimeErrors.ts
  packages/app-runtime/test/lib/TestUtil.ts
  packages/app-runtime/test/modules/SSEModule.test.ts
  packages/consumption/README.md
  packages/consumption/test/core/TestUtil.ts
  packages/content/README.md
  packages/content/test/attributeValues/NameValueTests.test.ts
  packages/core-types/README.md
  packages/runtime/README.md
  packages/runtime/src/Runtime.ts
  packages/runtime/src/dataViews/transport/MessageDVO.ts
  packages/runtime/src/events/transport/MessageDeliveredEvent.ts
  packages/runtime/src/useCases/common/RuntimeErrors.ts
  packages/runtime/src/useCases/transport/relationships/DecomposeRelationship.ts
  packages/runtime/test/anonymous/backboneCompatibility.test.ts
  packages/runtime/test/consumption/iqlQuery.test.ts
  packages/runtime/test/dataViews/DraftIdentityAttributeDVO.test.ts
  packages/runtime/test/lib/TestRuntime.ts
  packages/runtime/test/lib/testUtilsWithInactiveModules.ts
  packages/runtime/test/misc/CorrelationId.test.ts
  packages/runtime/test/transport/identityDeletionPeerProcessing.test.ts
  packages/transport/README.md
  packages/transport/package.json
  packages/transport/src/core/backbone/RESTClient.ts
  packages/transport/src/modules/accounts/AccountController.ts
  packages/transport/src/modules/devices/DeviceController.ts
  packages/transport/src/modules/devices/DeviceSecretController.ts
  packages/transport/src/modules/devices/DevicesController.ts
  packages/transport/src/modules/messages/MessageController.ts
  packages/transport/src/modules/secrets/SecretController.ts
  packages/transport/test/core/backbone/CorrelationId.test.ts
  packages/transport/test/modules/backboneCompatibility/BackboneCompatibilityController.test.ts
  packages/transport/test/modules/devices/DeviceDeletion.test.ts
  packages/transport/test/modules/devices/DeviceOnboarding.test.ts
  packages/transport/test/modules/files/FileController.test.ts
  packages/transport/test/modules/publicRelationshipTemplateReferences/PublicRelationshipTemplateReferencesController.test.ts
  packages/transport/test/modules/relationshipTemplates/RelationshipTemplateController.test.ts
  packages/transport/test/modules/sync/BackboneConcurrency.test.ts
  packages/transport/test/modules/tokens/AnonymousTokenController.test.ts
  packages/transport/test/modules/tokens/TokenController.test.ts
  packages/transport/test/testHelpers/TestUtil.ts
Labels: chore

#465 Prevent creation of peer shared IdentityAttribute duplicates by accepting a ShareAttributeRequestItem
  packages/consumption/src/modules/attributes/AttributesController.ts
  packages/consumption/src/modules/requests/itemProcessors/shareAttribute/ShareAttributeRequestItemProcessor.ts
  packages/consumption/test/modules/attributes/AttributesController.test.ts
  packages/consumption/test/modules/requests/itemProcessors/shareAttribute/ShareAttributeRequestItemProcessor.test.ts
Labels: enhancement
