Repository nmshd/runtime, pull requests merged in 2025-09, with the labels that each got.

#731 The FillDeviceOnboardingTokenWithNewDevice UseCase still does not accept url references
  packages/core-types/src/references/Reference.ts
  packages/core-types/test/references/Reference.test.ts
  packages/runtime/src/useCases/transport/devices/FillDeviceOnboardingTokenWithNewDevice.ts
  packages/runtime/test/transport/devices.test.ts
  packages/transport/test/modules/files/FileReference.test.ts
  packages/transport/test/modules/relationshipTemplates/RelationshipTemplateReference.test.ts
  packages/transport/test/modules/tokens/TokenReference.test.ts
Labels: bug

#732 Add possibility to update current device
  packages/runtime/src/extensibility/facades/transport/DevicesFacade.ts
  packages/runtime/src/useCases/common/Schemas.ts
  packages/runtime/src/useCases/transport/devices/UpdateCurrentDevice.ts
  packages/runtime/src/useCases/transport/devices/index.ts
  packages/runtime/test/transport/devices.test.ts
Labels: enhancement

#750 Remove deprecated device methods
  packages/app-runtime/src/AppStringProcessor.ts
  packages/app-runtime/test/modules/IdentityDeletionProcessStatusChangedModule.test.ts
  packages/app-runtime/test/runtime/AppStringProcessor.test.ts
  packages/app-runtime/test/runtime/Offboarding.test.ts
  packages/app-runtime/test/runtime/Onboarding.test.ts
  packages/runtime/src/extensibility/facades/transport/DevicesFacade.ts
  packages/runtime/src/useCases/common/Schemas.ts
  packages/runtime/src/useCases/transport/devices/CreateDevice.ts
  packages/runtime/src/useCases/transport/devices/CreateDeviceOnboardingToken.ts
  packages/runtime/src/useCases/transport/devices/GetDeviceOnboardingInfo.ts
  packages/runtime/src/useCases/transport/devices/index.ts
  packages/runtime/test/transport/account.test.ts
  packages/runtime/test/transport/devices.test.ts
  packages/runtime/test/transport/passwordProtection/deviceOnboardingToken.test.ts
Labels: breaking-change

#751 Re-add `processDeviceOnboardingReference` to the AppStringProcessor
  packages/app-runtime/src/AppStringProcessor.ts
  packages/app-runtime/test/runtime/AppStringProcessor.test.ts
Labels: bug

#760 Update test naming from receiver to recipient
  packages/runtime/test/consumption/requests.test.ts
  packages/runtime/test/lib/testUtilsWithInactiveModules.ts
Labels: test

#768 Move `PeerSharingDetailsJSON` to GetAttributes
  packages/consumption/src/modules/attributes/local/sharingDetails/PeerSharingDetails.ts
  packages/consumption/src/modules/attributes/local/sharingDetails/index.ts
  packages/runtime/src/useCases/consumption/attributes/GetAttributes.ts
Labels: refactoring

#770 Notify peers about Attribute deletion if only predecessor was shared
  packages/consumption/src/modules/attributes/AttributesController.ts
  packages/consumption/test/modules/attributes/AttributesController.test.ts
  packages/runtime/src/useCases/common/RuntimeErrors.ts
  packages/runtime/src/useCases/consumption/attributes/DeleteAttributeAndNotify.ts
  packages/runtime/test/consumption/attributes.test.ts
Labels: enhancement
