Repository nmshd/runtime, pull requests merged in 2025-05, with the labels that each got.

#503 Deny multiple module instances
  packages/runtime/src/Runtime.ts
  packages/runtime/src/extensibility/modules/RuntimeModule.ts
  packages/runtime/test/lib/RuntimeServiceProvider.ts
  packages/runtime/test/lib/TestRuntime.ts
  packages/runtime/test/modules/startup.test.ts
Labels: enhancement

#504 Validate tags in CanCreateRepositoryAttribute
  packages/runtime/src/useCases/consumption/attributes/CanCreateRepositoryAttribute.ts
  packages/runtime/test/consumption/attributes.test.ts
Labels: refactoring

#505 Resolve eslint excluded issues
  .eslintrc
  packages/consumption/test/modules/identityMetadata/IdentityMetadataController.test.ts
  packages/consumption/test/modules/requests/DecideRequestParametersValidator.test.ts
  packages/consumption/test/modules/requests/RequestItemProcessorRegistry.test.ts
  packages/consumption/test/modules/requests/itemProcessors/readAttribute/ReadAttributeRequestItemProcessor.test.ts
  packages/consumption/test/modules/requests/itemProcessors/shareAttribute/ShareAttributeRequestItemProcessor.test.ts
  packages/content/src/attributes/ThirdPartyRelationshipAttributeQuery.ts
  packages/content/test/attributeValues/ProprietaryJSON.test.ts
  packages/content/test/attributes/IQLQuery.test.ts
  packages/content/test/attributes/ThirdPartyRelationshipAttributeQuery.test.ts
  packages/runtime/test/consumption/requests.test.ts
  packages/runtime/test/lib/TestRuntime.ts
  packages/transport/src/modules/sync/SyncController.ts
  packages/transport/test/modules/account/AccountController.test.ts
  packages/transport/test/modules/secrets/SecretController.test.ts
  packages/transport/test/modules/sync/SyncController.ordered.test.ts
  packages/transport/test/modules/sync/SyncController.relationships.test.ts
  packages/transport/test/testHelpers/AdminApiClient.ts
  packages/transport/test/testHelpers/FakeSyncClient.ts
Labels: test

#506 Add validateTagsForType
  packages/consumption/src/modules/attributes/AttributesController.ts
  packages/consumption/src/modules/requests/itemProcessors/createAttribute/CreateAttributeRequestItemProcessor.ts
  packages/consumption/src/modules/requests/itemProcessors/proposeAttribute/ProposeAttributeRequestItemProcessor.ts
  packages/consumption/src/modules/requests/itemProcessors/readAttribute/ReadAttributeRequestItemProcessor.ts
  packages/consumption/src/modules/requests/itemProcessors/shareAttribute/ShareAttributeRequestItemProcessor.ts
  packages/consumption/test/modules/requests/itemProcessors/proposeAttribute/ProposeAttributeRequestItemProcessor.test.ts
  packages/consumption/test/modules/requests/itemProcessors/readAttribute/ReadAttributeRequestItemProcessor.test.ts
  packages/consumption/test/modules/requests/itemProcessors/shareAttribute/ShareAttributeRequestItemProcessor.test.ts
  packages/runtime/src/useCases/consumption/attributes/CanCreateRepositoryAttribute.ts
Labels: refactoring

#508 Test validation of successor
  packages/runtime/test/consumption/attributes.test.ts
Labels: test

#515 Update renovate config
  .github/renovate.json5
Labels: ci

#517 Add renovate rangeStrategy
  .github/renovate.json5
Labels: ci

#507 Validate tags of Files
  packages/consumption/src/modules/requests/itemProcessors/transferFileOwnership/TransferFileOwnershipRequestItemProcessor.ts
  packages/runtime/src/useCases/transport/files/UploadOwnFile.ts
  packages/runtime/test/transport/files.test.ts
Labels: enhancement

#522 Remove unused logger from SyncEverything
  packages/runtime/src/useCases/transport/account/SyncEverything.ts
Labels: refactoring

#520 Rename variable and make tests less dependent
  packages/runtime/src/modules/RequestModule.ts
  packages/runtime/test/transport/relationships.test.ts
Labels: refactoring

#524 Add the backboneBaseUrl to all truncated references
  packages/consumption/src/modules/requests/itemProcessors/transferFileOwnership/TransferFileOwnershipRequestItemProcessor.ts
  packages/consumption/test/core/TestUtil.ts
  packages/consumption/test/modules/requests/RequestEnd2End.test.ts
  packages/consumption/test/modules/requests/itemProcessors/transferFileOwnership/TransferFileOwnershipRequestItemProcessor.test.ts
  packages/content/src/attributes/types/strings/AbstractFileReference.ts
  packages/runtime/src/ConfigHolder.ts
  packages/runtime/src/Runtime.ts
  packages/runtime/src/useCases/transport/files/FileMapper.ts
  packages/runtime/src/useCases/transport/relationshipTemplates/RelationshipTemplateMapper.ts
  packages/runtime/src/useCases/transport/tokens/TokenMapper.ts
  packages/transport/src/modules/files/local/File.ts
  packages/transport/src/modules/messages/MessageController.ts
  packages/transport/src/modules/relationshipTemplates/local/RelationshipTemplate.ts
  packages/transport/src/modules/tokens/local/Token.ts
  packages/transport/test/end2end/End2End.test.ts
  packages/transport/test/modules/files/FileController.test.ts
  packages/transport/test/modules/relationshipTemplates/RelationshipTemplateController.test.ts
  packages/transport/test/modules/relationships/decomposition.test.ts
  packages/transport/test/modules/sync/SyncController.relationships.test.ts
  packages/transport/test/modules/tokens/AnonymousTokenController.test.ts
  packages/transport/test/modules/tokens/TokenController.test.ts
  packages/transport/test/testHelpers/TestUtil.ts
Labels: refactoring

#489 Provide truncated url
  packages/core-types/src/references/Reference.ts
  packages/core-types/test/references/Reference.test.ts
  packages/runtime/src/types/transport/FileDTO.ts
  packages/runtime/src/types/transport/RelationshipTemplateDTO.ts
  packages/runtime/src/types/transport/TokenDTO.ts
  packages/runtime/src/useCases/transport/files/FileMapper.ts
  packages/runtime/src/useCases/transport/relationshipTemplates/RelationshipTemplateMapper.ts
  packages/runtime/src/useCases/transport/tokens/TokenMapper.ts
Labels: wip, enhancement

#527 Remove truncatedReference from DTOs
  packages/app-runtime/test/lib/TestUtil.ts
  packages/app-runtime/test/modules/appEvents/RelationshipTemplateProcessedModule.test.ts
  packages/app-runtime/test/runtime/AppStringProcessor.test.ts
  packages/app-runtime/test/runtime/Onboarding.test.ts
  packages/runtime/src/dataViews/DataViewExpander.ts
  packages/runtime/src/types/transport/FileDTO.ts
  packages/runtime/src/types/transport/RelationshipTemplateDTO.ts
  packages/runtime/src/types/transport/TokenDTO.ts
  packages/runtime/src/useCases/transport/files/FileMapper.ts
  packages/runtime/src/useCases/transport/relationshipTemplates/RelationshipTemplateMapper.ts
  packages/runtime/src/useCases/transport/tokens/TokenMapper.ts
  packages/runtime/test/anonymous/tokens.test.ts
  packages/runtime/test/dataViews/IdentityDVO.test.ts
  packages/runtime/test/dataViews/RelationshipTemplateDVO.test.ts
  packages/runtime/test/dataViews/requestItems/TransferFileOwnershipRequestItemDVO.test.ts
  packages/runtime/test/lib/testUtils.ts
  packages/runtime/test/modules/DeciderModule.test.ts
  packages/runtime/test/modules/RequestModule.test.ts
  packages/runtime/test/transport/account.test.ts
  packages/runtime/test/transport/files.test.ts
  packages/runtime/test/transport/passwordProtection/deviceOnboardingToken.test.ts
  packages/runtime/test/transport/passwordProtection/files.test.ts
  packages/runtime/test/transport/passwordProtection/relationshipTemplates.test.ts
  packages/runtime/test/transport/passwordProtection/tokens.test.ts
  packages/runtime/test/transport/relationshipTemplates.test.ts
  packages/runtime/test/transport/tokens.test.ts
Labels: breaking-change, refactoring

#529 The AppStringProcessor error codes are not consistent
  packages/app-runtime/src/AppRuntimeErrors.ts
  packages/app-runtime/src/AppStringProcessor.ts
  packages/app-runtime/test/runtime/AppStringProcessor.test.ts
Labels: bug

#530 Test validation accepting a ReadAttributeRequestItem with a new Attribute
  packages/consumption/test/modules/requests/IncomingRequestsController.test.ts
  packages/consumption/test/modules/requests/itemProcessors/readAttribute/ReadAttributeRequestItemProcessor.test.ts
Labels: test

#531 Update the FileDVO to contain `reference.truncated` and `reference.url`
  packages/runtime/src/dataViews/DataViewExpander.ts
  packages/runtime/src/dataViews/transport/FileDVO.ts
  packages/runtime/test/dataViews/requestItems/TransferFileOwnershipRequestItemDVO.test.ts
Labels: bug

#534 Change location of test
  packages/consumption/test/modules/attributes/AttributesController.test.ts
Labels: test

#535 Allow url references with `nmshd(s)` schema
  packages/app-runtime/src/AppStringProcessor.ts
  packages/app-runtime/test/runtime/AppStringProcessor.test.ts
  packages/core-types/src/references/Reference.ts
  packages/core-types/test/references/Reference.test.ts
Labels: enhancement

#537 Remove deprecated methods and types
  packages/content/src/notifications/items/ThirdPartyRelationshipAttributeDeletedByPeerNotificationItem.ts
  packages/content/test/notifications/ThirdPartyRelationshipAttributeDeletedByPeerNotificationItem.test.ts
  packages/runtime/src/events/EventProxy.ts
  packages/runtime/src/events/consumption/ThirdPartyOwnedRelationshipAttributeDeletedByPeerEvent.ts
  packages/runtime/src/events/consumption/index.ts
  packages/runtime/src/extensibility/facades/consumption/AttributesFacade.ts
  packages/runtime/src/extensibility/facades/transport/AccountFacade.ts
  packages/runtime/test/consumption/attributes.test.ts
Labels: breaking-change

#525 Mark Attributes as deleted if Relationship is decomposed
  packages/consumption/src/consumption/ConsumptionCoreErrors.ts
  packages/consumption/src/modules/attributes/AttributesController.ts
  packages/runtime/src/extensibility/facades/consumption/AttributesFacade.ts
  packages/runtime/src/modules/RequestModule.ts
  packages/runtime/src/useCases/common/Schemas.ts
  packages/runtime/src/useCases/consumption/attributes/SetAttributeDeletionInfoOfDeletionProposedRelationship.ts
  packages/runtime/src/useCases/consumption/attributes/index.ts
  packages/runtime/test/consumption/attributes.test.ts
  packages/runtime/test/transport/relationships.test.ts
Labels: enhancement

#541 Make tag validation less breaking
  packages/consumption/src/modules/attributes/AttributesController.ts
  packages/consumption/test/modules/attributes/AttributesController.test.ts
  packages/consumption/test/modules/requests/itemProcessors/createAttribute/Context.ts
  packages/consumption/test/modules/requests/itemProcessors/createAttribute/CreateAttributeRequestItemProcessor.test.ts
  packages/consumption/test/modules/requests/itemProcessors/proposeAttribute/ProposeAttributeRequestItemProcessor.test.ts
  packages/consumption/test/modules/requests/itemProcessors/readAttribute/ReadAttributeRequestItemProcessor.test.ts
  packages/consumption/test/modules/requests/itemProcessors/shareAttribute/ShareAttributeRequestItemProcessor.test.ts
  packages/consumption/test/modules/requests/itemProcessors/transferFileOwnership/TransferFileOwnershipRequestItemProcessor.test.ts
  packages/consumption/test/modules/requests/itemProcessors/utility/validateAttributeMatchesWithQuery.test.ts
  packages/content/test/attributes/IQLQuery.test.ts
  packages/content/test/attributes/IdentityAttributeQuery.test.ts
  packages/runtime/test/consumption/attributes.test.ts
  packages/runtime/test/consumption/iqlQuery.test.ts
  packages/runtime/test/dataViews/IQLQueryExpanded.test.ts
  packages/runtime/test/dataViews/IdentityAttributeQueryExpanded.test.ts
  packages/runtime/test/dataViews/requestItems/ProposeAttributeRequestItemDVO.test.ts
  packages/runtime/test/dataViews/requestItems/ReadAttributeRequestItemDVO.test.ts
  packages/runtime/test/modules/DeciderModule.test.ts
  packages/runtime/test/transport/files.test.ts
Labels: enhancement

#544 Do not process nmshd links anymore
  packages/app-runtime/src/AppStringProcessor.ts
  packages/app-runtime/test/runtime/AppStringProcessor.test.ts
  packages/core-types/src/references/Reference.ts
  packages/core-types/test/references/Reference.test.ts
Labels: breaking-change

#546 Add TransferFileOwnershipAcceptResponseItem to AcceptResponseItemDerivation
  packages/content/src/requests/response/AcceptResponseItem.ts
  packages/runtime/src/useCases/common/Schemas.ts
Labels: chore

#548 Upgrade backbone
  .dev/compose.backbone.env
  .dev/compose.backbone.yml
  .github/renovate.json5
  package.json
  packages/app-runtime/test/lib/TestUtil.ts
  packages/transport/test/testHelpers/TestUtil.ts
Labels: ci

#549 Get rid of seed-database service in compose.backbone.yml
  .dev/appsettings.override.json
  .dev/compose.backbone.yml
Labels: test

#550 Handle the RelationshipTemplateAllocationsExhaustedExternalEvent
  packages/runtime/src/events/EventProxy.ts
  packages/runtime/src/events/transport/RelationshipTemplateAllocationsExhaustedEvent.ts
  packages/runtime/src/events/transport/index.ts
  packages/transport/src/events/RelationshipTemplateAllocationsExhaustedEvent.ts
  packages/transport/src/events/index.ts
  packages/transport/src/modules/sync/externalEventProcessors/ExternalEventProcessorRegistry.ts
  packages/transport/src/modules/sync/externalEventProcessors/RelationshipTemplateAllocationsExhaustedProcessor.ts
Labels: enhancement

#551 Adjust formatting and variable names in DataViewExpander
  packages/runtime/src/dataViews/DataViewExpander.ts
Labels: refactoring

#542 Announcements
  README_dev.md
  packages/runtime/src/Runtime.ts
  packages/runtime/src/extensibility/TransportServices.ts
  packages/runtime/src/extensibility/facades/transport/AnnouncementsFacade.ts
  packages/runtime/src/extensibility/facades/transport/index.ts
  packages/runtime/src/types/transport/AnnouncementDTO.ts
  packages/runtime/src/types/transport/index.ts
  packages/runtime/src/useCases/common/Schemas.ts
  packages/runtime/src/useCases/transport/announcements/AnnouncementMapper.ts
  packages/runtime/src/useCases/transport/announcements/GetAnnouncements.ts
  packages/runtime/src/useCases/transport/announcements/index.ts
  packages/runtime/src/useCases/transport/index.ts
  packages/runtime/test/lib/AdminApiClient.ts
  packages/runtime/test/transport/announcements.test.ts
  packages/transport/src/modules/accounts/AccountController.ts
  packages/transport/src/modules/announcements/AnnouncementController.ts
  packages/transport/src/modules/announcements/backbone/AnnouncementClient.ts
  packages/transport/src/modules/announcements/backbone/BackboneGetAnnouncements.ts
  packages/transport/src/modules/announcements/data/Announcement.ts
  packages/transport/src/modules/index.ts
  packages/transport/test/modules/announcements/AnnouncementController.test.ts
  packages/transport/test/testHelpers/AdminApiClient.ts
Labels: enhancement

#558 Cancelling the password prompt shows an error in the app
  packages/app-runtime/src/AppStringProcessor.ts
Labels: bug

#559 Add `isOwn` property to GetTokens use case
  packages/runtime/src/useCases/common/Schemas.ts
  packages/runtime/src/useCases/transport/tokens/GetTokens.ts
Labels: enhancement

#545 AttributeRequestItem can't be expanded if Attribute was deleted
  packages/runtime/src/dataViews/DataViewExpander.ts
  packages/runtime/src/dataViews/content/ResponseItemDVOs.ts
  packages/runtime/test/dataViews/requestItems/CreateIdentityAttributeRequestItemDVO.test.ts
  packages/runtime/test/dataViews/requestItems/ProposeAttributeRequestItemDVO.test.ts
  packages/runtime/test/dataViews/requestItems/ReadAttributeRequestItemDVO.test.ts
  packages/runtime/test/dataViews/requestItems/ShareAttributeRequestItemDVO.test.ts
  packages/runtime/test/dataViews/requestItems/TransferFileOwnershipRequestItemDVO.test.ts
Labels: bug

#560 Add processDeviceOnboardingReference to AppStringProcessor
  packages/app-runtime/src/AppRuntimeErrors.ts
  packages/app-runtime/src/AppStringProcessor.ts
  packages/app-runtime/test/runtime/AppStringProcessor.test.ts
Labels: enhancement

#561 Accounts in deletion are proposed in requestAccountSelection
  packages/app-runtime/src/AppStringProcessor.ts
Labels: bug

#562 `processDeviceOnboardingReference` is throwing when getting an invalid reference
  packages/app-runtime/src/AppStringProcessor.ts
Labels: bug

#563 Remove unused appruntime functionalities
  packages/app-runtime/src/AppRuntime.ts
  packages/app-runtime/src/AppRuntimeError.ts
  packages/app-runtime/src/AppRuntimeErrors.ts
  packages/app-runtime/src/AppRuntimeServices.ts
  packages/app-runtime/src/AppStringProcessor.ts
  packages/app-runtime/src/UserfriendlyApplicationError.ts
  packages/app-runtime/src/UserfriendlyResult.ts
  packages/app-runtime/src/extensibility/AppServices.ts
  packages/app-runtime/src/extensibility/DVOs/RelationshipItemsDVO.ts
  packages/app-runtime/src/extensibility/facades/AppRelationshipFacade.ts
  packages/app-runtime/src/extensibility/facades/AppRuntimeFacade.ts
  packages/app-runtime/src/extensibility/facades/index.ts
  packages/app-runtime/src/extensibility/index.ts
  packages/app-runtime/src/extensibility/ui/IUIBridge.ts
  packages/app-runtime/src/index.ts
  packages/app-runtime/src/modules/PushNotificationModule.ts
  packages/app-runtime/src/modules/appEvents/MailReceivedModule.ts
  packages/app-runtime/src/modules/appEvents/OnboardingChangeReceivedModule.ts
  packages/app-runtime/src/modules/appEvents/RelationshipTemplateProcessedModule.ts
  packages/app-runtime/src/modules/runtimeEvents/IdentityDeletionProcessStatusChangedModule.ts
  packages/app-runtime/src/modules/runtimeEvents/MessageReceivedModule.ts
  packages/app-runtime/src/modules/runtimeEvents/RelationshipChangedModule.ts
  packages/app-runtime/src/multiAccount/data/LocalAccountSession.ts
  packages/app-runtime/src/natives/INativeTranslationProvider.ts
  packages/app-runtime/src/natives/index.ts
  packages/app-runtime/test/extensibility/AppRelationshipFacade.test.ts
  packages/app-runtime/test/extensibility/MessageFacade.test.ts
  packages/app-runtime/test/lib/MockUIBridge.ts
  packages/app-runtime/test/runtime/Offboarding.test.ts
  packages/app-runtime/test/runtime/Onboarding.test.ts
  packages/app-runtime/test/runtime/TranslationProvider.test.ts
Labels: bug

#566 Add getPushToken to NativeNotificationAccess
  packages/app-runtime/src/modules/PushNotificationModule.ts
  packages/app-runtime/src/natives/INativeConfigAccess.ts
  packages/app-runtime/src/natives/INativeEnvironment.ts
  packages/app-runtime/src/natives/INativeNotificationAccess.ts
  packages/app-runtime/src/natives/index.ts
  packages/app-runtime/test/lib/natives/FakeNativeBootstrapper.ts
  packages/app-runtime/test/lib/natives/FakeNativeConfigAccess.ts
  packages/app-runtime/test/lib/natives/FakeNativeNotificationAccess.ts
Labels: enhancement

#567 Refactor DeciderModule
  packages/runtime/src/modules/DeciderModule.ts
Labels: refactoring

#554 Enforce uniqueness of IdentityAttribute and File `tags`, Message `recipients` and Message `attachments`
  packages/content/src/attributes/IdentityAttribute.ts
  packages/content/src/attributes/IdentityAttributeQuery.ts
  packages/content/test/attributes/IdentityAttribute.test.ts
  packages/runtime/src/useCases/common/Schemas.ts
  packages/runtime/src/useCases/transport/files/UploadOwnFile.ts
  packages/runtime/src/useCases/transport/messages/SendMessage.ts
  packages/runtime/test/transport/files.test.ts
  packages/runtime/test/transport/messages.test.ts
Labels: enhancement

#572 Unused `cannotSetWasAutomaticallyDecided` error code
  packages/consumption/src/consumption/ConsumptionCoreErrors.ts
Labels: bug

#571 Add `wasAutomaticallyDecided` query parameter to use case for querying incoming Requests
  packages/runtime/src/useCases/common/Schemas.ts
  packages/runtime/src/useCases/consumption/requests/GetIncomingRequests.ts
Labels: enhancement

#577 RequestStatusChanged events are not published for expired requests
  packages/consumption/src/modules/requests/incoming/IncomingRequestsController.ts
  packages/consumption/src/modules/requests/outgoing/OutgoingRequestsController.ts
  packages/runtime/test/consumption/requests.test.ts
Labels: bug
