Repository nmshd/runtime, pull requests merged in 2025-04, with the labels that each got.

#473 NotFound error is logged when handling relationship status changed external event after the relationship has been decomposed
  .dev/compose.backbone.env
  package-lock.json
  packages/transport/src/modules/relationships/RelationshipsController.ts
  packages/transport/src/modules/sync/externalEventProcessors/RelationshipReactivationCompletedExternalEventProcessor.ts
  packages/transport/src/modules/sync/externalEventProcessors/RelationshipReactivationRequestedExternalEventProcessor.ts
  packages/transport/src/modules/sync/externalEventProcessors/RelationshipStatusChangedExternalEventProcessor.ts
  packages/transport/test/modules/sync/SyncController.relationships.test.ts
Labels: bug

#478 Test failures
  packages/consumption/test/modules/requests/itemProcessors/proposeAttribute/ProposeAttributeRequestItemProcessor.test.ts
  packages/consumption/test/modules/requests/itemProcessors/readAttribute/ReadAttributeRequestItemProcessor.test.ts
  packages/transport/test/modules/sync/SyncController.relationships.test.ts
Labels: test

#479 Sync fails when receiving unknown external event
  packages/transport/src/modules/sync/SyncController.ts
  packages/transport/test/modules/sync/SyncController.error.test.ts
Labels: bug

#463 Add caching of tags
  package-lock.json
  packages/consumption/package.json
  packages/consumption/src/modules/attributes/AttributesController.ts
  packages/consumption/test/core/TestUtil.ts
  packages/consumption/test/modules/attributes/AttributeTagCollection.test.ts
  packages/consumption/test/modules/attributes/AttributesController.test.ts
  packages/runtime/test/consumption/attributeTagCollection.test.ts
  packages/transport/src/core/Transport.ts
  packages/transport/src/core/backbone/ClientResult.ts
  packages/transport/src/core/backbone/PlatformParameters.ts
  packages/transport/src/core/backbone/RESTClient.ts
  packages/transport/src/modules/tags/backbone/TagClient.ts
Labels: enhancement

#475 Add FormFieldRequestItem
  packages/consumption/src/consumption/ConsumptionController.ts
  packages/consumption/src/modules/requests/index.ts
  packages/consumption/src/modules/requests/itemProcessors/formField/AcceptFormFieldRequestItemParameters.ts
  packages/consumption/src/modules/requests/itemProcessors/formField/FormFieldRequestItemProcessor.ts
  packages/consumption/test/modules/requests/itemProcessors/formField/FormFieldRequestItemProcessor.test.ts
  packages/content/src/attributes/ThirdPartyRelationshipAttributeQuery.ts
  packages/content/src/requests/RequestItem.ts
  packages/content/src/requests/items/formField/FormFieldAcceptResponseItem.ts
  packages/content/src/requests/items/formField/FormFieldRequestItem.ts
  packages/content/src/requests/items/formField/settings/BooleanFormFieldSettings.ts
  packages/content/src/requests/items/formField/settings/DateFormFieldSettings.ts
  packages/content/src/requests/items/formField/settings/DoubleFormFieldSettings.ts
  packages/content/src/requests/items/formField/settings/FormFieldSettings.ts
  packages/content/src/requests/items/formField/settings/FormFieldSettingsDerivations.ts
  packages/content/src/requests/items/formField/settings/IntegerFormFieldSettings.ts
  packages/content/src/requests/items/formField/settings/RatingFormFieldSettings.ts
  packages/content/src/requests/items/formField/settings/SelectionFormFieldSettings.ts
  packages/content/src/requests/items/formField/settings/StringFormFieldSettings.ts
  packages/content/src/requests/items/formField/settings/index.ts
  packages/content/src/requests/items/index.ts
  packages/content/src/requests/response/AcceptResponseItem.ts
  packages/content/test/requests/items/FormFieldAcceptResponseItem.test.ts
  packages/content/test/requests/items/FormFieldRequestItem.test.ts
  packages/runtime/src/dataViews/DataViewExpander.ts
  packages/runtime/src/dataViews/consumption/DecidableRequestItemDVOs.ts
  packages/runtime/src/dataViews/content/RequestItemDVOs.ts
  packages/runtime/src/dataViews/content/ResponseItemDVOs.ts
  packages/runtime/src/useCases/common/Schemas.ts
  packages/runtime/test/dataViews/requestItems/FormFieldRequestItemDVO.test.ts
Labels: enhancement

#484 Allow longer tags
  packages/content/src/attributes/IdentityAttribute.ts
  packages/content/src/attributes/IdentityAttributeQuery.ts
Labels: enhancement

#485 Add sendMailDisabled to RelationshipDVO
  packages/runtime/src/dataViews/DataViewExpander.ts
  packages/runtime/src/dataViews/transport/RelationshipDVO.ts
  packages/runtime/test/dataViews/RelationshipDVO.test.ts
  packages/runtime/test/lib/testUtils.ts
Labels: enhancement

#487 Remove QR code UseCases and make the runtime slim
  package-lock.json
  packages/runtime/package.json
  packages/runtime/src/extensibility/facades/transport/FilesFacade.ts
  packages/runtime/src/extensibility/facades/transport/RelationshipTemplatesFacade.ts
  packages/runtime/src/extensibility/facades/transport/TokensFacade.ts
  packages/runtime/src/useCases/common/QRCode.ts
  packages/runtime/src/useCases/common/Schemas.ts
  packages/runtime/src/useCases/common/index.ts
  packages/runtime/src/useCases/transport/files/CreateQRCodeForFile.ts
  packages/runtime/src/useCases/transport/files/CreateTokenQRCodeForFile.ts
  packages/runtime/src/useCases/transport/files/index.ts
  packages/runtime/src/useCases/transport/relationshipTemplates/CreateQRCodeForOwnRelationshipTemplate.ts
  packages/runtime/src/useCases/transport/relationshipTemplates/CreateTokenQRCodeForOwnRelationshipTemplate.ts
  packages/runtime/src/useCases/transport/relationshipTemplates/index.ts
  packages/runtime/src/useCases/transport/tokens/GetQRCodeForToken.ts
  packages/runtime/src/useCases/transport/tokens/index.ts
  packages/runtime/test/lib/testUtils.ts
  packages/runtime/test/transport/files.test.ts
  packages/runtime/test/transport/relationshipTemplates.test.ts
Labels: enhancement

#488 Remove more QR code wordings
  packages/runtime/src/useCases/common/RuntimeErrors.ts
  packages/runtime/test/transport/relationshipTemplates.test.ts
Labels: chore

#490 Remove `title` from RequestItem
  packages/content/src/requests/RequestItem.ts
  packages/content/src/requests/items/authentication/AuthenticationRequestItem.ts
  packages/content/src/requests/items/formField/FormFieldRequestItem.ts
  packages/content/test/requests/Request.test.ts
  packages/runtime/src/dataViews/DataViewExpander.ts
  packages/runtime/src/modules/decide/RequestConfig.ts
  packages/runtime/src/useCases/common/Schemas.ts
  packages/runtime/src/useCases/consumption/attributes/CreateAndShareRelationshipAttribute.ts
  packages/runtime/src/useCases/consumption/attributes/ShareRepositoryAttribute.ts
  packages/runtime/test/consumption/attributes.test.ts
  packages/runtime/test/modules/DeciderModule.test.ts
Labels: breaking-change

#492 Update test naming
  packages/consumption/test/modules/requests/itemProcessors/formField/FormFieldRequestItemProcessor.test.ts
Labels: test

#493 Automatically decide AuthenticationRequestItem with configured `title`
  packages/runtime/test/modules/DeciderModule.test.ts
Labels: test

#497 Missing type annotation in `ConsentJSON`
  packages/content/src/attributes/types/relationship/Consent.ts
  packages/runtime/src/useCases/common/Schemas.ts
Labels: bug

#499 Delete unused error
  packages/transport/src/core/TransportCoreErrors.ts
Labels: chore

#498 Check validation error message explicitly
  packages/runtime/test/transport/passwordProtection/deviceOnboardingToken.test.ts
  packages/runtime/test/transport/passwordProtection/files.test.ts
  packages/runtime/test/transport/passwordProtection/relationshipTemplates.test.ts
  packages/runtime/test/transport/passwordProtection/tokens.test.ts
Labels: test

#500 It is possible to set `0` as PasswordLocationIndicator
  packages/runtime/src/useCases/common/validation/TokenAndTemplateCreationValidator.ts
  packages/runtime/test/common/TokenAndTemplateCreationValidator.test.ts
  packages/runtime/test/transport/passwordProtection/deviceOnboardingToken.test.ts
  packages/runtime/test/transport/passwordProtection/files.test.ts
  packages/runtime/test/transport/passwordProtection/relationshipTemplates.test.ts
  packages/runtime/test/transport/passwordProtection/tokens.test.ts
Labels: bug

#502 Unify undefined checks
  packages/app-runtime/src/modules/SSEModule.ts
  packages/consumption/src/modules/requests/itemProcessors/createAttribute/CreateAttributeRequestItemProcessor.ts
  packages/consumption/src/modules/requests/itemProcessors/proposeAttribute/ProposeAttributeRequestItemProcessor.ts
  packages/consumption/src/modules/requests/itemProcessors/readAttribute/ReadAttributeRequestItemProcessor.ts
  packages/consumption/src/modules/requests/itemProcessors/shareAttribute/ShareAttributeRequestItemProcessor.ts
  packages/consumption/src/modules/requests/itemProcessors/transferFileOwnership/TransferFileOwnershipRequestItemProcessor.ts
  packages/consumption/src/modules/requests/itemProcessors/utility/validateAttributeMatchesWithQuery.ts
  packages/content/src/attributes/types/relationship/Consent.ts
  packages/content/src/requests/items/consent/ConsentRequestItem.ts
  packages/content/src/requests/items/proposeAttribute/ProposeAttributeRequestItem.ts
  packages/runtime/src/modules/DeciderModule.ts
  packages/runtime/src/useCases/common/PasswordProtectionMapper.ts
Labels: refactoring

#501 Rename createTokenForOwnRelationshipTemplate
  packages/runtime/src/extensibility/facades/transport/RelationshipTemplatesFacade.ts
  packages/runtime/src/useCases/common/Schemas.ts
  packages/runtime/src/useCases/transport/relationshipTemplates/CreateTokenForOwnRelationshipTemplate.ts
  packages/runtime/test/transport/account.test.ts
  packages/runtime/test/transport/passwordProtection/relationshipTemplates.test.ts
  packages/runtime/test/transport/relationshipTemplates.test.ts
Labels: refactoring
