Repository nmshd/runtime, pull requests merged in 2025-06, with the labels that each got.

#580 Support `ownershipToken` of Files
  packages/app-runtime/test/lib/TestUtil.ts
  packages/runtime/src/events/EventProxy.ts
  packages/runtime/src/events/transport/FileOwnershipLockedEvent.ts
  packages/runtime/src/events/transport/index.ts
  packages/runtime/src/extensibility/facades/transport/FilesFacade.ts
  packages/runtime/src/types/transport/FileDTO.ts
  packages/runtime/src/useCases/common/RuntimeErrors.ts
  packages/runtime/src/useCases/common/Schemas.ts
  packages/runtime/src/useCases/transport/account/SyncEverything.ts
  packages/runtime/src/useCases/transport/files/FileMapper.ts
  packages/runtime/src/useCases/transport/files/RegenerateFileOwnershipToken.ts
  packages/runtime/src/useCases/transport/files/index.ts
  packages/runtime/test/lib/testUtils.ts
  packages/runtime/test/transport/files.test.ts
  packages/transport/src/core/backbone/RESTClient.ts
  packages/transport/src/core/backbone/RESTClientAuthenticate.ts
  packages/transport/src/core/backbone/RequestError.ts
  packages/transport/src/events/FileOwnershipLockedEvent.ts
  packages/transport/src/events/index.ts
  packages/transport/src/modules/files/FileController.ts
  packages/transport/src/modules/files/backbone/BackbonePostFiles.ts
  packages/transport/src/modules/files/backbone/FileClient.ts
  packages/transport/src/modules/files/local/File.ts
  packages/transport/src/modules/sync/ChangedItems.ts
  packages/transport/src/modules/sync/externalEventProcessors/ExternalEventProcessor.ts
  packages/transport/src/modules/sync/externalEventProcessors/ExternalEventProcessorRegistry.ts
  packages/transport/src/modules/sync/externalEventProcessors/FileOwnershipLockedExternalEventProcessor.ts
  packages/transport/test/modules/files/FileController.test.ts
  packages/transport/test/testHelpers/TestUtil.ts
Labels: enhancement

#585 Bump backbone to `6.46.0`
  .dev/compose.backbone.yml
  packages/transport/src/modules/announcements/AnnouncementController.ts
  packages/transport/src/modules/announcements/backbone/BackboneGetAnnouncements.ts
  packages/transport/src/modules/announcements/data/Announcement.ts
  packages/transport/test/modules/files/FileController.test.ts
Labels: dependencies

#587 Move File uploads into tests
  package-lock.json
  packages/consumption/test/modules/requests/itemProcessors/transferFileOwnership/TransferFileOwnershipRequestItemProcessor.test.ts
Labels: test

#588 Handle FileOwnershipClaimed external event
  .dev/compose.backbone.yml
  packages/runtime/src/events/EventProxy.ts
  packages/runtime/src/events/transport/FileOwnershipClaimedEvent.ts
  packages/runtime/src/events/transport/index.ts
  packages/transport/src/events/FileOwnershipClaimedEvent.ts
  packages/transport/src/events/index.ts
  packages/transport/src/modules/files/local/File.ts
  packages/transport/src/modules/sync/externalEventProcessors/ExternalEventProcessorRegistry.ts
  packages/transport/src/modules/sync/externalEventProcessors/FileOwnershipClaimedExternalEventProcessor.ts
  packages/transport/src/modules/sync/externalEventProcessors/FileOwnershipLockedExternalEventProcessor.ts
  packages/transport/test/modules/files/FileController.test.ts
Labels: enhancement

#591 Add test for not being able to claim own file
  .dev/compose.backbone.yml
  packages/transport/test/modules/files/FileController.test.ts
Labels: test

#589 Transfer File ownership using `ownershipToken`
  packages/consumption/src/modules/requests/itemProcessors/transferFileOwnership/TransferFileOwnershipRequestItemProcessor.ts
  packages/consumption/test/modules/requests/itemProcessors/transferFileOwnership/TransferFileOwnershipRequestItemProcessor.test.ts
  packages/content/src/requests/items/transferFileOwnership/TransferFileOwnershipRequestItem.ts
  packages/runtime/src/dataViews/content/RequestItemDVOs.ts
  packages/runtime/src/useCases/common/Schemas.ts
  packages/runtime/test/dataViews/requestItems/TransferFileOwnershipRequestItemDVO.test.ts
Labels: enhancement

#592 Audit exclude
  .ci/runChecks.sh
  package-lock.json
Labels: chore

#593 Audit fix
  .ci/runChecks.sh
  package-lock.json
Labels: chore

#602 The ownership of the original File might not be transferred using a TransferFileOwnershipRequestItem
  packages/consumption/src/modules/requests/itemProcessors/transferFileOwnership/TransferFileOwnershipRequestItemProcessor.ts
  packages/consumption/test/modules/requests/itemProcessors/transferFileOwnership/TransferFileOwnershipRequestItemProcessor.test.ts
  packages/content/src/requests/items/transferFileOwnership/TransferFileOwnershipRequestItem.ts
  packages/content/test/requests/items/TransferFileOwnershipRequestItem.test.ts
  packages/runtime/src/dataViews/content/RequestItemDVOs.ts
  packages/runtime/src/useCases/common/Schemas.ts
  packages/runtime/test/modules/DeciderModule.test.ts
Labels: breaking-change, bug

#608 Use barrel imports
  packages/transport/src/events/MessageDeliveredEvent.ts
  packages/transport/src/events/MessageReceivedEvent.ts
  packages/transport/src/events/MessageSentEvent.ts
  packages/transport/src/events/MessageWasReadAtChangedEvent.ts
  packages/transport/src/events/PeerRelationshipTemplateLoadedEvent.ts
  packages/transport/src/events/RelationshipChangedEvent.ts
  packages/transport/src/events/RelationshipReactivationCompletedEvent.ts
  packages/transport/src/events/RelationshipReactivationRequestedEvent.ts
  packages/transport/src/events/RelationshipTemplateAllocationsExhaustedEvent.ts
Labels: refactoring

#610 Make Files tests independent
  packages/runtime/test/lib/testUtils.ts
  packages/runtime/test/transport/files.test.ts
Labels: test

#613 Simplify tests for creating incoming Request
  packages/consumption/test/modules/requests/IncomingRequestsController.test.ts
  packages/consumption/test/modules/requests/RequestsIntegrationTest.ts
Labels: test

#611 Add `wasViewed` for Files
  packages/runtime/src/dataViews/transport/FileDVO.ts
  packages/runtime/src/events/EventProxy.ts
  packages/runtime/src/events/transport/FileWasViewedEvent.ts
  packages/runtime/src/events/transport/index.ts
  packages/runtime/src/extensibility/facades/transport/FilesFacade.ts
  packages/runtime/src/types/transport/FileDTO.ts
  packages/runtime/src/useCases/common/Schemas.ts
  packages/runtime/src/useCases/transport/files/FileMapper.ts
  packages/runtime/src/useCases/transport/files/GetFiles.ts
  packages/runtime/src/useCases/transport/files/MarkFileAsViewed.ts
  packages/runtime/src/useCases/transport/files/index.ts
  packages/runtime/test/transport/files.test.ts
  packages/transport/src/events/FileWasViewedEvent.ts
  packages/transport/src/events/index.ts
  packages/transport/src/modules/files/FileController.ts
  packages/transport/src/modules/files/local/File.ts
  packages/transport/test/modules/files/FileController.test.ts
Labels: enhancement

#612 Multiple Requests with the same `id` can be created
  packages/consumption/src/consumption/ConsumptionCoreErrors.ts
  packages/consumption/src/modules/requests/incoming/IncomingRequestsController.ts
  packages/consumption/test/modules/requests/IncomingRequestsController.test.ts
  packages/runtime/src/useCases/common/RuntimeErrors.ts
  packages/runtime/src/useCases/transport/messages/SendMessage.ts
  packages/runtime/test/transport/messages.test.ts
Labels: bug

#622 Test File ownership events
  packages/consumption/test/core/TestUtil.ts
  packages/consumption/test/modules/requests/itemProcessors/transferFileOwnership/TransferFileOwnershipRequestItemProcessor.test.ts
  packages/transport/test/modules/files/FileController.test.ts
Labels: test

#626 Simplify and test the AppLanguageModule
  packages/app-runtime/src/AppRuntime.ts
  packages/app-runtime/src/events/AppLanguageChangedEvent.ts
  packages/app-runtime/src/infrastructure/IAppLanguageProvider.ts
  packages/app-runtime/src/infrastructure/index.ts
  packages/app-runtime/src/modules/AppLanguageModule.ts
  packages/app-runtime/test/lib/TestUtil.ts
  packages/app-runtime/test/lib/infrastructure/FakeAppLanguageProvider.ts
  packages/app-runtime/test/lib/infrastructure/MockAppLanguageProvider.ts
  packages/app-runtime/test/modules/AppLanguage.test.ts
  packages/runtime/src/useCases/common/Schemas.ts
  packages/runtime/src/useCases/transport/devices/SetCommunicationLanguage.ts
  packages/transport/src/modules/devices/backbone/BackboneGetDevices.ts
  packages/transport/src/modules/devices/backbone/DeviceAuthClient.ts
Labels: refactoring, test
